// Code generated by tools/generate.v; DO NOT EDIT.
module ast

// NodeFlags stores Prism node flags as a bitset.
pub type NodeFlags = u32

// node_flag_newline indicates that a node starts on a new line.
pub const node_flag_newline = NodeFlags(0x1)

// node_flag_static_literal indicates that a node is a static literal.
pub const node_flag_static_literal = NodeFlags(0x2)

// has reports whether this bitset contains flag.
pub fn (flags NodeFlags) has(flag NodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// has_flag reports whether this node base contains flag.
pub fn (base NodeBase) has_flag(flag NodeFlags) bool {
	return base.flags.has(flag)
}

// ArgumentsNodeFlags flags for arguments nodes.
pub type ArgumentsNodeFlags = u32

// if the arguments contain forwarding
pub const arguments_node_contains_forwarding = ArgumentsNodeFlags(1 << 2)

// if the arguments contain keywords
pub const arguments_node_contains_keywords = ArgumentsNodeFlags(1 << 3)

// if the arguments contain a keyword splat
pub const arguments_node_contains_keyword_splat = ArgumentsNodeFlags(1 << 4)

// if the arguments contain a splat
pub const arguments_node_contains_splat = ArgumentsNodeFlags(1 << 5)

// if the arguments contain multiple splats
pub const arguments_node_contains_multiple_splats = ArgumentsNodeFlags(1 << 6)

// has reports whether this bitset contains flag.
pub fn (flags ArgumentsNodeFlags) has(flag ArgumentsNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags ArgumentsNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// ArrayNodeFlags flags for array nodes.
pub type ArrayNodeFlags = u32

// if array contains splat nodes
pub const array_node_contains_splat = ArrayNodeFlags(1 << 2)

// has reports whether this bitset contains flag.
pub fn (flags ArrayNodeFlags) has(flag ArrayNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags ArrayNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// CallNodeFlags flags for call nodes.
pub type CallNodeFlags = u32

// &. operator
pub const call_node_safe_navigation = CallNodeFlags(1 << 2)

// a call that could have been a local variable
pub const call_node_variable_call = CallNodeFlags(1 << 3)

// a call that is an attribute write, so the value being written should be returned
pub const call_node_attribute_write = CallNodeFlags(1 << 4)

// a call that ignores method visibility
pub const call_node_ignore_visibility = CallNodeFlags(1 << 5)

// has reports whether this bitset contains flag.
pub fn (flags CallNodeFlags) has(flag CallNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags CallNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// EncodingFlags flags for nodes that have unescaped content.
pub type EncodingFlags = u32

// internal bytes forced the encoding to UTF-8
pub const encoding_forced_utf8_encoding = EncodingFlags(1 << 2)

// internal bytes forced the encoding to binary
pub const encoding_forced_binary_encoding = EncodingFlags(1 << 3)

// has reports whether this bitset contains flag.
pub fn (flags EncodingFlags) has(flag EncodingFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags EncodingFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// IntegerBaseFlags flags for integer nodes that correspond to the base of the integer.
pub type IntegerBaseFlags = u32

// 0b prefix
pub const integer_base_binary = IntegerBaseFlags(1 << 2)

// 0d or no prefix
pub const integer_base_decimal = IntegerBaseFlags(1 << 3)

// 0o or 0 prefix
pub const integer_base_octal = IntegerBaseFlags(1 << 4)

// 0x prefix
pub const integer_base_hexadecimal = IntegerBaseFlags(1 << 5)

// has reports whether this bitset contains flag.
pub fn (flags IntegerBaseFlags) has(flag IntegerBaseFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags IntegerBaseFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// InterpolatedStringNodeFlags flags for interpolated string nodes that indicated mutability if they are also marked as literals.
pub type InterpolatedStringNodeFlags = u32

// frozen by virtue of a `frozen_string_literal: true` comment or `--enable-frozen-string-literal`; only for adjacent string literals like `'a' 'b'`
pub const interpolated_string_node_frozen = InterpolatedStringNodeFlags(1 << 2)

// mutable by virtue of a `frozen_string_literal: false` comment or `--disable-frozen-string-literal`; only for adjacent string literals like `'a' 'b'`
pub const interpolated_string_node_mutable = InterpolatedStringNodeFlags(1 << 3)

// has reports whether this bitset contains flag.
pub fn (flags InterpolatedStringNodeFlags) has(flag InterpolatedStringNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags InterpolatedStringNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// KeywordHashNodeFlags flags for keyword hash nodes.
pub type KeywordHashNodeFlags = u32

// a keyword hash which only has `AssocNode` elements all with symbol keys, which means the elements can be treated as keyword arguments
pub const keyword_hash_node_symbol_keys = KeywordHashNodeFlags(1 << 2)

// has reports whether this bitset contains flag.
pub fn (flags KeywordHashNodeFlags) has(flag KeywordHashNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags KeywordHashNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// LoopFlags flags for while and until loop nodes.
pub type LoopFlags = u32

// a loop after a begin statement, so the body is executed first before the condition
pub const loop_begin_modifier = LoopFlags(1 << 2)

// has reports whether this bitset contains flag.
pub fn (flags LoopFlags) has(flag LoopFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags LoopFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// ParameterFlags flags for parameter nodes.
pub type ParameterFlags = u32

// a parameter name that has been repeated in the method signature
pub const parameter_repeated_parameter = ParameterFlags(1 << 2)

// has reports whether this bitset contains flag.
pub fn (flags ParameterFlags) has(flag ParameterFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags ParameterFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// ParenthesesNodeFlags flags for parentheses nodes.
pub type ParenthesesNodeFlags = u32

// parentheses that contain multiple potentially void statements
pub const parentheses_node_multiple_statements = ParenthesesNodeFlags(1 << 2)

// has reports whether this bitset contains flag.
pub fn (flags ParenthesesNodeFlags) has(flag ParenthesesNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags ParenthesesNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// RangeFlags flags for range and flip-flop nodes.
pub type RangeFlags = u32

// ... operator
pub const range_exclude_end = RangeFlags(1 << 2)

// has reports whether this bitset contains flag.
pub fn (flags RangeFlags) has(flag RangeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags RangeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// RegularExpressionFlags flags for regular expression and match last line nodes.
pub type RegularExpressionFlags = u32

// i - ignores the case of characters when matching
pub const regular_expression_ignore_case = RegularExpressionFlags(1 << 2)

// x - ignores whitespace and allows comments in regular expressions
pub const regular_expression_extended = RegularExpressionFlags(1 << 3)

// m - allows $ to match the end of lines within strings
pub const regular_expression_multi_line = RegularExpressionFlags(1 << 4)

// o - only interpolates values into the regular expression once
pub const regular_expression_once = RegularExpressionFlags(1 << 5)

// e - forces the EUC-JP encoding
pub const regular_expression_euc_jp = RegularExpressionFlags(1 << 6)

// n - forces the ASCII-8BIT encoding
pub const regular_expression_ascii_8bit = RegularExpressionFlags(1 << 7)

// s - forces the Windows-31J encoding
pub const regular_expression_windows_31j = RegularExpressionFlags(1 << 8)

// u - forces the UTF-8 encoding
pub const regular_expression_utf_8 = RegularExpressionFlags(1 << 9)

// internal bytes forced the encoding to UTF-8
pub const regular_expression_forced_utf8_encoding = RegularExpressionFlags(1 << 10)

// internal bytes forced the encoding to binary
pub const regular_expression_forced_binary_encoding = RegularExpressionFlags(1 << 11)

// internal bytes forced the encoding to US-ASCII
pub const regular_expression_forced_us_ascii_encoding = RegularExpressionFlags(1 << 12)

// has reports whether this bitset contains flag.
pub fn (flags RegularExpressionFlags) has(flag RegularExpressionFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags RegularExpressionFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// ShareableConstantNodeFlags flags for shareable constant nodes.
pub type ShareableConstantNodeFlags = u32

// constant writes that should be modified with shareable constant value literal
pub const shareable_constant_node_literal = ShareableConstantNodeFlags(1 << 2)

// constant writes that should be modified with shareable constant value experimental everything
pub const shareable_constant_node_experimental_everything = ShareableConstantNodeFlags(1 << 3)

// constant writes that should be modified with shareable constant value experimental copy
pub const shareable_constant_node_experimental_copy = ShareableConstantNodeFlags(1 << 4)

// has reports whether this bitset contains flag.
pub fn (flags ShareableConstantNodeFlags) has(flag ShareableConstantNodeFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags ShareableConstantNodeFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// StringFlags flags for string nodes.
pub type StringFlags = u32

// internal bytes forced the encoding to UTF-8
pub const string_forced_utf8_encoding = StringFlags(1 << 2)

// internal bytes forced the encoding to binary
pub const string_forced_binary_encoding = StringFlags(1 << 3)

// frozen by virtue of a `frozen_string_literal: true` comment or `--enable-frozen-string-literal`
pub const string_frozen = StringFlags(1 << 4)

// mutable by virtue of a `frozen_string_literal: false` comment or `--disable-frozen-string-literal`
pub const string_mutable = StringFlags(1 << 5)

// has reports whether this bitset contains flag.
pub fn (flags StringFlags) has(flag StringFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags StringFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// SymbolFlags flags for symbol nodes.
pub type SymbolFlags = u32

// internal bytes forced the encoding to UTF-8
pub const symbol_forced_utf8_encoding = SymbolFlags(1 << 2)

// internal bytes forced the encoding to binary
pub const symbol_forced_binary_encoding = SymbolFlags(1 << 3)

// internal bytes forced the encoding to US-ASCII
pub const symbol_forced_us_ascii_encoding = SymbolFlags(1 << 4)

// has reports whether this bitset contains flag.
pub fn (flags SymbolFlags) has(flag SymbolFlags) bool {
	return u32(flags) & u32(flag) != 0
}

// node_flags returns this typed bitset as common node flags.
pub fn (flags SymbolFlags) node_flags() NodeFlags {
	return NodeFlags(flags)
}

// flags_value returns typed flags for ArgumentsNode.
pub fn (node ArgumentsNode) flags_value() ArgumentsNodeFlags {
	return ArgumentsNodeFlags(node.base.flags)
}

// has_flag reports whether ArgumentsNode has flag.
pub fn (node ArgumentsNode) has_flag(flag ArgumentsNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for ArrayNode.
pub fn (node ArrayNode) flags_value() ArrayNodeFlags {
	return ArrayNodeFlags(node.base.flags)
}

// has_flag reports whether ArrayNode has flag.
pub fn (node ArrayNode) has_flag(flag ArrayNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for BlockLocalVariableNode.
pub fn (node BlockLocalVariableNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether BlockLocalVariableNode has flag.
pub fn (node BlockLocalVariableNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for BlockParameterNode.
pub fn (node BlockParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether BlockParameterNode has flag.
pub fn (node BlockParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for CallAndWriteNode.
pub fn (node CallAndWriteNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether CallAndWriteNode has flag.
pub fn (node CallAndWriteNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for CallNode.
pub fn (node CallNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether CallNode has flag.
pub fn (node CallNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for CallOperatorWriteNode.
pub fn (node CallOperatorWriteNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether CallOperatorWriteNode has flag.
pub fn (node CallOperatorWriteNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for CallOrWriteNode.
pub fn (node CallOrWriteNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether CallOrWriteNode has flag.
pub fn (node CallOrWriteNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for CallTargetNode.
pub fn (node CallTargetNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether CallTargetNode has flag.
pub fn (node CallTargetNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for FlipFlopNode.
pub fn (node FlipFlopNode) flags_value() RangeFlags {
	return RangeFlags(node.base.flags)
}

// has_flag reports whether FlipFlopNode has flag.
pub fn (node FlipFlopNode) has_flag(flag RangeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for IndexAndWriteNode.
pub fn (node IndexAndWriteNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether IndexAndWriteNode has flag.
pub fn (node IndexAndWriteNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for IndexOperatorWriteNode.
pub fn (node IndexOperatorWriteNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether IndexOperatorWriteNode has flag.
pub fn (node IndexOperatorWriteNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for IndexOrWriteNode.
pub fn (node IndexOrWriteNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether IndexOrWriteNode has flag.
pub fn (node IndexOrWriteNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for IndexTargetNode.
pub fn (node IndexTargetNode) flags_value() CallNodeFlags {
	return CallNodeFlags(node.base.flags)
}

// has_flag reports whether IndexTargetNode has flag.
pub fn (node IndexTargetNode) has_flag(flag CallNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for IntegerNode.
pub fn (node IntegerNode) flags_value() IntegerBaseFlags {
	return IntegerBaseFlags(node.base.flags)
}

// has_flag reports whether IntegerNode has flag.
pub fn (node IntegerNode) has_flag(flag IntegerBaseFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for InterpolatedMatchLastLineNode.
pub fn (node InterpolatedMatchLastLineNode) flags_value() RegularExpressionFlags {
	return RegularExpressionFlags(node.base.flags)
}

// has_flag reports whether InterpolatedMatchLastLineNode has flag.
pub fn (node InterpolatedMatchLastLineNode) has_flag(flag RegularExpressionFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for InterpolatedRegularExpressionNode.
pub fn (node InterpolatedRegularExpressionNode) flags_value() RegularExpressionFlags {
	return RegularExpressionFlags(node.base.flags)
}

// has_flag reports whether InterpolatedRegularExpressionNode has flag.
pub fn (node InterpolatedRegularExpressionNode) has_flag(flag RegularExpressionFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for InterpolatedStringNode.
pub fn (node InterpolatedStringNode) flags_value() InterpolatedStringNodeFlags {
	return InterpolatedStringNodeFlags(node.base.flags)
}

// has_flag reports whether InterpolatedStringNode has flag.
pub fn (node InterpolatedStringNode) has_flag(flag InterpolatedStringNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for KeywordHashNode.
pub fn (node KeywordHashNode) flags_value() KeywordHashNodeFlags {
	return KeywordHashNodeFlags(node.base.flags)
}

// has_flag reports whether KeywordHashNode has flag.
pub fn (node KeywordHashNode) has_flag(flag KeywordHashNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for KeywordRestParameterNode.
pub fn (node KeywordRestParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether KeywordRestParameterNode has flag.
pub fn (node KeywordRestParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for MatchLastLineNode.
pub fn (node MatchLastLineNode) flags_value() RegularExpressionFlags {
	return RegularExpressionFlags(node.base.flags)
}

// has_flag reports whether MatchLastLineNode has flag.
pub fn (node MatchLastLineNode) has_flag(flag RegularExpressionFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for OptionalKeywordParameterNode.
pub fn (node OptionalKeywordParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether OptionalKeywordParameterNode has flag.
pub fn (node OptionalKeywordParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for OptionalParameterNode.
pub fn (node OptionalParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether OptionalParameterNode has flag.
pub fn (node OptionalParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for ParenthesesNode.
pub fn (node ParenthesesNode) flags_value() ParenthesesNodeFlags {
	return ParenthesesNodeFlags(node.base.flags)
}

// has_flag reports whether ParenthesesNode has flag.
pub fn (node ParenthesesNode) has_flag(flag ParenthesesNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for RangeNode.
pub fn (node RangeNode) flags_value() RangeFlags {
	return RangeFlags(node.base.flags)
}

// has_flag reports whether RangeNode has flag.
pub fn (node RangeNode) has_flag(flag RangeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for RationalNode.
pub fn (node RationalNode) flags_value() IntegerBaseFlags {
	return IntegerBaseFlags(node.base.flags)
}

// has_flag reports whether RationalNode has flag.
pub fn (node RationalNode) has_flag(flag IntegerBaseFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for RegularExpressionNode.
pub fn (node RegularExpressionNode) flags_value() RegularExpressionFlags {
	return RegularExpressionFlags(node.base.flags)
}

// has_flag reports whether RegularExpressionNode has flag.
pub fn (node RegularExpressionNode) has_flag(flag RegularExpressionFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for RequiredKeywordParameterNode.
pub fn (node RequiredKeywordParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether RequiredKeywordParameterNode has flag.
pub fn (node RequiredKeywordParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for RequiredParameterNode.
pub fn (node RequiredParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether RequiredParameterNode has flag.
pub fn (node RequiredParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for RestParameterNode.
pub fn (node RestParameterNode) flags_value() ParameterFlags {
	return ParameterFlags(node.base.flags)
}

// has_flag reports whether RestParameterNode has flag.
pub fn (node RestParameterNode) has_flag(flag ParameterFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for ShareableConstantNode.
pub fn (node ShareableConstantNode) flags_value() ShareableConstantNodeFlags {
	return ShareableConstantNodeFlags(node.base.flags)
}

// has_flag reports whether ShareableConstantNode has flag.
pub fn (node ShareableConstantNode) has_flag(flag ShareableConstantNodeFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for SourceFileNode.
pub fn (node SourceFileNode) flags_value() StringFlags {
	return StringFlags(node.base.flags)
}

// has_flag reports whether SourceFileNode has flag.
pub fn (node SourceFileNode) has_flag(flag StringFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for StringNode.
pub fn (node StringNode) flags_value() StringFlags {
	return StringFlags(node.base.flags)
}

// has_flag reports whether StringNode has flag.
pub fn (node StringNode) has_flag(flag StringFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for SymbolNode.
pub fn (node SymbolNode) flags_value() SymbolFlags {
	return SymbolFlags(node.base.flags)
}

// has_flag reports whether SymbolNode has flag.
pub fn (node SymbolNode) has_flag(flag SymbolFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for UntilNode.
pub fn (node UntilNode) flags_value() LoopFlags {
	return LoopFlags(node.base.flags)
}

// has_flag reports whether UntilNode has flag.
pub fn (node UntilNode) has_flag(flag LoopFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for WhileNode.
pub fn (node WhileNode) flags_value() LoopFlags {
	return LoopFlags(node.base.flags)
}

// has_flag reports whether WhileNode has flag.
pub fn (node WhileNode) has_flag(flag LoopFlags) bool {
	return node.flags_value().has(flag)
}

// flags_value returns typed flags for XStringNode.
pub fn (node XStringNode) flags_value() EncodingFlags {
	return EncodingFlags(node.base.flags)
}

// has_flag reports whether XStringNode has flag.
pub fn (node XStringNode) has_flag(flag EncodingFlags) bool {
	return node.flags_value().has(flag)
}
