// Code generated by tools/generate.v; DO NOT EDIT.
module ast

// Node contains every concrete Prism AST node.
pub type Node = AliasGlobalVariableNode
	| AliasMethodNode
	| AlternationPatternNode
	| AndNode
	| ArgumentsNode
	| ArrayNode
	| ArrayPatternNode
	| AssocNode
	| AssocSplatNode
	| BackReferenceReadNode
	| BeginNode
	| BlockArgumentNode
	| BlockLocalVariableNode
	| BlockNode
	| BlockParameterNode
	| BlockParametersNode
	| BreakNode
	| CallAndWriteNode
	| CallNode
	| CallOperatorWriteNode
	| CallOrWriteNode
	| CallTargetNode
	| CapturePatternNode
	| CaseMatchNode
	| CaseNode
	| ClassNode
	| ClassVariableAndWriteNode
	| ClassVariableOperatorWriteNode
	| ClassVariableOrWriteNode
	| ClassVariableReadNode
	| ClassVariableTargetNode
	| ClassVariableWriteNode
	| ConstantAndWriteNode
	| ConstantOperatorWriteNode
	| ConstantOrWriteNode
	| ConstantPathAndWriteNode
	| ConstantPathNode
	| ConstantPathOperatorWriteNode
	| ConstantPathOrWriteNode
	| ConstantPathTargetNode
	| ConstantPathWriteNode
	| ConstantReadNode
	| ConstantTargetNode
	| ConstantWriteNode
	| DefNode
	| DefinedNode
	| ElseNode
	| EmbeddedStatementsNode
	| EmbeddedVariableNode
	| EnsureNode
	| FalseNode
	| FindPatternNode
	| FlipFlopNode
	| FloatNode
	| ForNode
	| ForwardingArgumentsNode
	| ForwardingParameterNode
	| ForwardingSuperNode
	| GlobalVariableAndWriteNode
	| GlobalVariableOperatorWriteNode
	| GlobalVariableOrWriteNode
	| GlobalVariableReadNode
	| GlobalVariableTargetNode
	| GlobalVariableWriteNode
	| HashNode
	| HashPatternNode
	| IfNode
	| ImaginaryNode
	| ImplicitNode
	| ImplicitRestNode
	| InNode
	| IndexAndWriteNode
	| IndexOperatorWriteNode
	| IndexOrWriteNode
	| IndexTargetNode
	| InstanceVariableAndWriteNode
	| InstanceVariableOperatorWriteNode
	| InstanceVariableOrWriteNode
	| InstanceVariableReadNode
	| InstanceVariableTargetNode
	| InstanceVariableWriteNode
	| IntegerNode
	| InterpolatedMatchLastLineNode
	| InterpolatedRegularExpressionNode
	| InterpolatedStringNode
	| InterpolatedSymbolNode
	| InterpolatedXStringNode
	| ItLocalVariableReadNode
	| ItParametersNode
	| KeywordHashNode
	| KeywordRestParameterNode
	| LambdaNode
	| LocalVariableAndWriteNode
	| LocalVariableOperatorWriteNode
	| LocalVariableOrWriteNode
	| LocalVariableReadNode
	| LocalVariableTargetNode
	| LocalVariableWriteNode
	| MatchLastLineNode
	| MatchPredicateNode
	| MatchRequiredNode
	| MatchWriteNode
	| MissingNode
	| ModuleNode
	| MultiTargetNode
	| MultiWriteNode
	| NextNode
	| NilNode
	| NoKeywordsParameterNode
	| NumberedParametersNode
	| NumberedReferenceReadNode
	| OptionalKeywordParameterNode
	| OptionalParameterNode
	| OrNode
	| ParametersNode
	| ParenthesesNode
	| PinnedExpressionNode
	| PinnedVariableNode
	| PostExecutionNode
	| PreExecutionNode
	| ProgramNode
	| RangeNode
	| RationalNode
	| RedoNode
	| RegularExpressionNode
	| RequiredKeywordParameterNode
	| RequiredParameterNode
	| RescueModifierNode
	| RescueNode
	| RestParameterNode
	| RetryNode
	| ReturnNode
	| SelfNode
	| ShareableConstantNode
	| SingletonClassNode
	| SourceEncodingNode
	| SourceFileNode
	| SourceLineNode
	| SplatNode
	| StatementsNode
	| StringNode
	| SuperNode
	| SymbolNode
	| TrueNode
	| UndefNode
	| UnlessNode
	| UntilNode
	| WhenNode
	| WhileNode
	| XStringNode
	| YieldNode

// AliasGlobalVariableNode represents the use of the `alias` keyword to alias a global variable.
//
//     alias $foo $bar
//     ^^^^^^^^^^^^^^^
pub struct AliasGlobalVariableNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the new name of the global variable that can be used after aliasing.
	//
	//     alias $foo $bar
	//           ^^^^
	new_name Node

	// Represents the old name of the global variable that can be used before aliasing.
	//
	//     alias $foo $bar
	//                ^^^^
	old_name Node

	// The location of the `alias` keyword.
	//
	//     alias $foo $bar
	//     ^^^^^
	keyword_loc Location
}

// AliasMethodNode represents the use of the `alias` keyword to alias a method.
//
//     alias foo bar
//     ^^^^^^^^^^^^^
pub struct AliasMethodNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the new name of the method that will be aliased.
	//
	//     alias foo bar
	//           ^^^
	//
	//     alias :foo :bar
	//           ^^^^
	//
	//     alias :"#{foo}" :"#{bar}"
	//           ^^^^^^^^^
	new_name Node

	// Represents the old name of the method that will be aliased.
	//
	//     alias foo bar
	//               ^^^
	//
	//     alias :foo :bar
	//                ^^^^
	//
	//     alias :"#{foo}" :"#{bar}"
	//                     ^^^^^^^^^
	old_name Node

	// Represents the location of the `alias` keyword.
	//
	//     alias foo bar
	//     ^^^^^
	keyword_loc Location
}

// AlternationPatternNode represents an alternation pattern in pattern matching.
//
//     foo => bar | baz
//            ^^^^^^^^^
pub struct AlternationPatternNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the left side of the expression.
	//
	//     foo => bar | baz
	//            ^^^
	left Node

	// Represents the right side of the expression.
	//
	//     foo => bar | baz
	//                  ^^^
	right Node

	// Represents the alternation operator location.
	//
	//     foo => bar | baz
	//                ^
	operator_loc Location
}

// AndNode represents the use of the `&&` operator or the `and` keyword.
//
//     left and right
//     ^^^^^^^^^^^^^^
pub struct AndNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the left side of the expression. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     left and right
	//     ^^^^
	//
	//     1 && 2
	//     ^
	left Node

	// Represents the right side of the expression.
	//
	//     left && right
	//             ^^^^^
	//
	//     1 and 2
	//           ^
	right Node

	// The location of the `and` keyword or the `&&` operator.
	//
	//     left and right
	//          ^^^
	operator_loc Location
}

// ArgumentsNode represents a set of arguments to a method or a keyword.
//
//     return foo, bar, baz
//            ^^^^^^^^^^^^^
pub struct ArgumentsNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The list of arguments, if present. These can be any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo(bar, baz)
	//         ^^^^^^^^
	arguments []Node
}

// ArrayNode represents an array literal. This can be a regular array using brackets or a special array using % like %w or %i.
//
//     [1, 2, 3]
//     ^^^^^^^^^
pub struct ArrayNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represent the list of zero or more [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md
	elements []Node

	// Represents the optional source location for the opening token.
	//
	//     [1,2,3]                 # "["
	//     %w[foo bar baz]         # "%w["
	//     %I(apple orange banana) # "%I("
	//     foo = 1, 2, 3           # nil
	opening_loc ?Location

	// Represents the optional source location for the closing token.
	//
	//     [1,2,3]                 # "]"
	//     %w[foo bar baz]         # "]"
	//     %I(apple orange banana) # ")"
	//     foo = 1, 2, 3           # nil
	closing_loc ?Location
}

// ArrayPatternNode represents an array pattern in pattern matching.
//
//     foo in 1, 2
//     ^^^^^^^^^^^
//
//     foo in [1, 2]
//     ^^^^^^^^^^^^^
//
//     foo in *bar
//     ^^^^^^^^^^^
//
//     foo in Bar[]
//     ^^^^^^^^^^^^
//
//     foo in Bar[1, 2, 3]
//     ^^^^^^^^^^^^^^^^^^^
pub struct ArrayPatternNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the optional constant preceding the Array
	//
	//     foo in Bar[]
	//            ^^^
	//
	//     foo in Bar[1, 2, 3]
	//            ^^^
	//
	//     foo in Bar::Baz[1, 2, 3]
	//            ^^^^^^^^
	constant ?Node

	// Represents the required elements of the array pattern.
	//
	//     foo in [1, 2]
	//             ^  ^
	requireds []Node

	// Represents the rest element of the array pattern.
	//
	//     foo in *bar
	//            ^^^^
	rest ?Node

	// Represents the elements after the rest element of the array pattern.
	//
	//     foo in *bar, baz
	//                  ^^^
	posts []Node

	// Represents the opening location of the array pattern.
	//
	//     foo in [1, 2]
	//            ^
	opening_loc ?Location

	// Represents the closing location of the array pattern.
	//
	//     foo in [1, 2]
	//                 ^
	closing_loc ?Location
}

// AssocNode represents a hash key/value pair.
//
//     { a => b }
//       ^^^^^^
pub struct AssocNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The key of the association. This can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     { a: b }
	//       ^
	//
	//     { foo => bar }
	//       ^^^
	//
	//     { def a; end => 1 }
	//       ^^^^^^^^^^
	key Node

	// The value of the association, if present. This can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     { foo => bar }
	//              ^^^
	//
	//     { x: 1 }
	//          ^
	value Node

	// The location of the `=>` operator, if present.
	//
	//     { foo => bar }
	//           ^^
	operator_loc ?Location
}

// AssocSplatNode represents a splat in a hash literal.
//
//     { **foo }
//       ^^^^^
pub struct AssocSplatNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The value to be splatted, if present. Will be missing when keyword rest argument forwarding is used.
	//
	//     { **foo }
	//         ^^^
	value ?Node

	// The location of the `**` operator.
	//
	//     { **x }
	//       ^^
	operator_loc Location
}

// BackReferenceReadNode represents reading a reference to a field in the previous match.
//
//     $'
//     ^^
pub struct BackReferenceReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the back-reference variable, including the leading `$`.
	//
	//     $& # name `:$&`
	//
	//     $+ # name `:$+`
	name ConstantId
}

// BeginNode represents a begin statement.
//
//     begin
//       foo
//     end
//     ^^^^^
pub struct BeginNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the location of the `begin` keyword.
	//
	//     begin x end
	//     ^^^^^
	begin_keyword_loc ?Location

	// Represents the statements within the begin block.
	//
	//     begin x end
	//           ^
	statements ?Node

	// Represents the rescue clause within the begin block.
	//
	//     begin x; rescue y; end
	//              ^^^^^^^^
	rescue_clause ?Node

	// Represents the else clause within the begin block.
	//
	//     begin x; rescue y; else z; end
	//                        ^^^^^^
	else_clause ?Node

	// Represents the ensure clause within the begin block.
	//
	//     begin x; ensure y; end
	//              ^^^^^^^^
	ensure_clause ?Node

	// Represents the location of the `end` keyword.
	//
	//     begin x end
	//             ^^^
	end_keyword_loc ?Location
}

// BlockArgumentNode represents a block argument using `&`.
//
//     bar(&args)
//     ^^^^^^^^^^
pub struct BlockArgumentNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The expression that is being passed as a block argument. This can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo(&args)
	//         ^^^^^
	expression ?Node

	// Represents the location of the `&` operator.
	//
	//     foo(&args)
	//         ^
	operator_loc Location
}

// BlockLocalVariableNode represents a block local variable.
//
//     a { |; b| }
//            ^
pub struct BlockLocalVariableNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the block local variable.
	//
	//     a { |; b| } # name `:b`
	//            ^
	name ConstantId
}

// BlockNode represents a block of ruby code.
//
//     [1, 2, 3].each { |i| puts x }
//                    ^^^^^^^^^^^^^^
pub struct BlockNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The local variables declared in the block.
	//
	//     [1, 2, 3].each { |i| puts x } # locals: [:i]
	//                       ^
	locals []ConstantId

	// The parameters of the block.
	//
	//     [1, 2, 3].each { |i| puts x }
	//                      ^^^
	//     [1, 2, 3].each { puts _1 }
	//                    ^^^^^^^^^^^
	//     [1, 2, 3].each { puts it }
	//                    ^^^^^^^^^^^
	parameters ?Node

	// The body of the block.
	//
	//     [1, 2, 3].each { |i| puts x }
	//                          ^^^^^^
	body ?Node

	// Represents the location of the opening `{` or `do`.
	//
	//     [1, 2, 3].each { |i| puts x }
	//                    ^
	opening_loc Location

	// Represents the location of the closing `}` or `end`.
	//
	//     [1, 2, 3].each { |i| puts x }
	//                                 ^
	closing_loc Location
}

// BlockParameterNode represents a block parameter of a method, block, or lambda definition.
//
//     def a(&b)
//           ^^
//     end
pub struct BlockParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the block parameter.
	//
	//     def a(&b) # name `:b`
	//            ^
	//     end
	name ?ConstantId

	// Represents the location of the block parameter name.
	//
	//     def a(&b)
	//            ^
	name_loc ?Location

	// Represents the location of the `&` operator.
	//
	//     def a(&b)
	//           ^
	//     end
	operator_loc Location
}

// BlockParametersNode represents a block's parameters declaration.
//
//     -> (a, b = 1; local) { }
//        ^^^^^^^^^^^^^^^^^
//
//     foo do |a, b = 1; local|
//            ^^^^^^^^^^^^^^^^^
//     end
pub struct BlockParametersNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the parameters of the block.
	//
	//     -> (a, b = 1; local) { }
	//         ^^^^^^^^
	//
	//     foo do |a, b = 1; local|
	//             ^^^^^^^^
	//     end
	parameters ?Node

	// Represents the local variables of the block.
	//
	//     -> (a, b = 1; local) { }
	//                   ^^^^^
	//
	//     foo do |a, b = 1; local|
	//                       ^^^^^
	//     end
	locals []Node

	// Represents the opening location of the block parameters.
	//
	//     -> (a, b = 1; local) { }
	//        ^
	//
	//     foo do |a, b = 1; local|
	//            ^
	//     end
	opening_loc ?Location

	// Represents the closing location of the block parameters.
	//
	//     -> (a, b = 1; local) { }
	//                        ^
	//
	//     foo do |a, b = 1; local|
	//                            ^
	//     end
	closing_loc ?Location
}

// BreakNode represents the use of the `break` keyword.
//
//     break foo
//     ^^^^^^^^^
pub struct BreakNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The arguments to the break statement, if present. These can be any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     break foo
	//           ^^^
	arguments ?Node

	// The location of the `break` keyword.
	//
	//     break foo
	//     ^^^^^
	keyword_loc Location
}

// CallAndWriteNode represents the use of the `&&=` operator on a call.
//
//     foo.bar &&= value
//     ^^^^^^^^^^^^^^^^^
pub struct CallAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The object that the method is being called on. This can be either `nil` or any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo.bar &&= value
	//     ^^^
	receiver ?Node

	// Represents the location of the call operator.
	//
	//     foo.bar &&= value
	//        ^
	call_operator_loc ?Location

	// Represents the location of the message.
	//
	//     foo.bar &&= value
	//         ^^^
	message_loc ?Location

	// Represents the name of the method being called.
	//
	//     foo.bar &&= value # read_name `:bar`
	//         ^^^
	read_name ConstantId

	// Represents the name of the method being written to.
	//
	//     foo.bar &&= value # write_name `:bar=`
	//         ^^^
	write_name ConstantId

	// Represents the location of the operator.
	//
	//     foo.bar &&= value
	//             ^^^
	operator_loc Location

	// Represents the value being assigned.
	//
	//     foo.bar &&= value
	//                 ^^^^^
	value Node
}

// CallNode represents a method call, in all of the various forms that can take.
//
//     foo
//     ^^^
//
//     foo()
//     ^^^^^
//
//     +foo
//     ^^^^
//
//     foo + bar
//     ^^^^^^^^^
//
//     foo.bar
//     ^^^^^^^
//
//     foo&.bar
//     ^^^^^^^^
pub struct CallNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The object that the method is being called on. This can be either `nil` or any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo.bar
	//     ^^^
	//
	//     +foo
	//      ^^^
	//
	//     foo + bar
	//     ^^^
	receiver ?Node

	// Represents the location of the call operator.
	//
	//     foo.bar
	//        ^
	//
	//     foo&.bar
	//        ^^
	call_operator_loc ?Location

	// Represents the name of the method being called.
	//
	//     foo.bar # name `:foo`
	//     ^^^
	name ConstantId

	// Represents the location of the message.
	//
	//     foo.bar
	//         ^^^
	message_loc ?Location

	// Represents the location of the left parenthesis.
	//     foo(bar)
	//        ^
	opening_loc ?Location

	// Represents the arguments to the method call. These can be any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo(bar)
	//         ^^^
	arguments ?Node

	// Represents the location of the right parenthesis.
	//
	//     foo(bar)
	//            ^
	closing_loc ?Location

	// Represents the location of the equal sign, in the case that this is an attribute write.
	//
	//     foo.bar = value
	//             ^
	//
	//     foo[bar] = value
	//              ^
	equal_loc ?Location

	// Represents the block that is being passed to the method.
	//
	//     foo { |a| a }
	//         ^^^^^^^^^
	block ?Node
}

// CallOperatorWriteNode represents the use of an assignment operator on a call.
//
//     foo.bar += baz
//     ^^^^^^^^^^^^^^
pub struct CallOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The object that the method is being called on. This can be either `nil` or any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo.bar += value
	//     ^^^
	receiver ?Node

	// Represents the location of the call operator.
	//
	//     foo.bar += value
	//        ^
	call_operator_loc ?Location

	// Represents the location of the message.
	//
	//     foo.bar += value
	//         ^^^
	message_loc ?Location

	// Represents the name of the method being called.
	//
	//     foo.bar += value # read_name `:bar`
	//         ^^^
	read_name ConstantId

	// Represents the name of the method being written to.
	//
	//     foo.bar += value # write_name `:bar=`
	//         ^^^
	write_name ConstantId

	// Represents the binary operator being used.
	//
	//     foo.bar += value # binary_operator `:+`
	//             ^
	binary_operator ConstantId

	// Represents the location of the binary operator.
	//
	//     foo.bar += value
	//             ^^
	binary_operator_loc Location

	// Represents the value being assigned.
	//
	//     foo.bar += value
	//                ^^^^^
	value Node
}

// CallOrWriteNode represents the use of the `||=` operator on a call.
//
//     foo.bar ||= value
//     ^^^^^^^^^^^^^^^^^
pub struct CallOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The object that the method is being called on. This can be either `nil` or any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo.bar ||= value
	//     ^^^
	receiver ?Node

	// Represents the location of the call operator.
	//
	//     foo.bar ||= value
	//        ^
	call_operator_loc ?Location

	// Represents the location of the message.
	//
	//     foo.bar ||= value
	//         ^^^
	message_loc ?Location

	// Represents the name of the method being called.
	//
	//     foo.bar ||= value # read_name `:bar`
	//         ^^^
	read_name ConstantId

	// Represents the name of the method being written to.
	//
	//     foo.bar ||= value # write_name `:bar=`
	//         ^^^
	write_name ConstantId

	// Represents the location of the operator.
	//
	//     foo.bar ||= value
	//             ^^^
	operator_loc Location

	// Represents the value being assigned.
	//
	//     foo.bar ||= value
	//                 ^^^^^
	value Node
}

// CallTargetNode represents assigning to a method call.
//
//     foo.bar, = 1
//     ^^^^^^^
//
//     begin
//     rescue => foo.bar
//               ^^^^^^^
//     end
//
//     for foo.bar in baz do end
//         ^^^^^^^
pub struct CallTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The object that the method is being called on. This can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo.bar = 1
	//     ^^^
	receiver Node

	// Represents the location of the call operator.
	//
	//     foo.bar = 1
	//        ^
	call_operator_loc Location

	// Represents the name of the method being called.
	//
	//     foo.bar = 1 # name `:foo`
	//     ^^^
	name ConstantId

	// Represents the location of the message.
	//
	//     foo.bar = 1
	//         ^^^
	message_loc Location
}

// CapturePatternNode represents assigning to a local variable in pattern matching.
//
//     foo => [bar => baz]
//            ^^^^^^^^^^^^
pub struct CapturePatternNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the value to capture.
	//
	//     foo => bar
	//            ^^^
	value Node

	// Represents the target of the capture.
	//
	//     foo => bar
	//     ^^^
	target Node

	// Represents the location of the `=>` operator.
	//
	//     foo => bar
	//         ^^
	operator_loc Location
}

// CaseMatchNode represents the use of a case statement for pattern matching.
//
//     case true
//     in false
//     end
//     ^^^^^^^^^
pub struct CaseMatchNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the predicate of the case match. This can be either `nil` or any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     case true; in false; end
	//     ^^^^
	predicate ?Node

	// Represents the conditions of the case match.
	//
	//     case true; in false; end
	//                ^^^^^^^^
	conditions []Node

	// Represents the else clause of the case match.
	//
	//     case true; in false; else; end
	//                          ^^^^
	else_clause ?Node

	// Represents the location of the `case` keyword.
	//
	//     case true; in false; end
	//     ^^^^
	case_keyword_loc Location

	// Represents the location of the `end` keyword.
	//
	//     case true; in false; end
	//                          ^^^
	end_keyword_loc Location
}

// CaseNode represents the use of a case statement.
//
//     case true
//     when false
//     end
//     ^^^^^^^^^^
pub struct CaseNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the predicate of the case statement. This can be either `nil` or any [non-void expressions](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     case true; when false; end
	//          ^^^^
	predicate ?Node

	// Represents the conditions of the case statement.
	//
	//     case true; when false; end
	//                ^^^^^^^^^^
	conditions []Node

	// Represents the else clause of the case statement.
	//
	//     case true; when false; else; end
	//                            ^^^^
	else_clause ?Node

	// Represents the location of the `case` keyword.
	//
	//     case true; when false; end
	//     ^^^^
	case_keyword_loc Location

	// Represents the location of the `end` keyword.
	//
	//     case true; when false; end
	//                            ^^^
	end_keyword_loc Location
}

// ClassNode represents a class declaration involving the `class` keyword.
//
//     class Foo end
//     ^^^^^^^^^^^^^
pub struct ClassNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	locals []ConstantId

	// Represents the location of the `class` keyword.
	//
	//     class Foo end
	//     ^^^^^
	class_keyword_loc Location

	constant_path Node

	// Represents the location of the `<` operator.
	//
	//     class Foo < Bar
	//               ^
	inheritance_operator_loc ?Location

	// Represents the superclass of the class.
	//
	//     class Foo < Bar
	//                 ^^^
	superclass ?Node

	// Represents the body of the class.
	//
	//     class Foo
	//       foo
	//       ^^^
	body ?Node

	// Represents the location of the `end` keyword.
	//
	//     class Foo end
	//               ^^^
	end_keyword_loc Location

	// The name of the class.
	//
	//     class Foo end # name `:Foo`
	name ConstantId
}

// ClassVariableAndWriteNode represents the use of the `&&=` operator for assignment to a class variable.
//
//     @@target &&= value
//     ^^^^^^^^^^^^^^^^^^
pub struct ClassVariableAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the class variable, which is a `@@` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     @@target &&= value # name `:@@target`
	//     ^^^^^^^^
	name ConstantId

	// Represents the location of the variable name.
	//
	//     @@target &&= value
	//     ^^^^^^^^
	name_loc Location

	// Represents the location of the `&&=` operator.
	//
	//     @@target &&= value
	//              ^^^
	operator_loc Location

	// Represents the value being assigned. This can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     @@target &&= value
	//                  ^^^^^
	value Node
}

// ClassVariableOperatorWriteNode represents assigning to a class variable using an operator that isn't `=`.
//
//     @@target += value
//     ^^^^^^^^^^^^^^^^^
pub struct ClassVariableOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name                ConstantId
	name_loc            Location
	binary_operator_loc Location
	value               Node
	binary_operator     ConstantId
}

// ClassVariableOrWriteNode represents the use of the `||=` operator for assignment to a class variable.
//
//     @@target ||= value
//     ^^^^^^^^^^^^^^^^^^
pub struct ClassVariableOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// ClassVariableReadNode represents referencing a class variable.
//
//     @@foo
//     ^^^^^
pub struct ClassVariableReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the class variable, which is a `@@` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     @@abc   # name `:@@abc`
	//
	//     @@_test # name `:@@_test`
	name ConstantId
}

// ClassVariableTargetNode represents writing to a class variable in a context that doesn't have an explicit value.
//
//     @@foo, @@bar = baz
//     ^^^^^  ^^^^^
pub struct ClassVariableTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name ConstantId
}

// ClassVariableWriteNode represents writing to a class variable.
//
//     @@foo = 1
//     ^^^^^^^^^
pub struct ClassVariableWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the class variable, which is a `@@` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     @@abc = 123     # name `@@abc`
	//
	//     @@_test = :test # name `@@_test`
	name ConstantId

	// The location of the variable name.
	//
	//     @@foo = :bar
	//     ^^^^^
	name_loc Location

	// The value to write to the class variable. This can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     @@foo = :bar
	//             ^^^^
	//
	//     @@_xyz = 123
	//              ^^^
	value Node

	// The location of the `=` operator.
	//
	//     @@foo = :bar
	//           ^
	operator_loc Location
}

// ConstantAndWriteNode represents the use of the `&&=` operator for assignment to a constant.
//
//     Target &&= value
//     ^^^^^^^^^^^^^^^^
pub struct ConstantAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// ConstantOperatorWriteNode represents assigning to a constant using an operator that isn't `=`.
//
//     Target += value
//     ^^^^^^^^^^^^^^^
pub struct ConstantOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name                ConstantId
	name_loc            Location
	binary_operator_loc Location
	value               Node
	binary_operator     ConstantId
}

// ConstantOrWriteNode represents the use of the `||=` operator for assignment to a constant.
//
//     Target ||= value
//     ^^^^^^^^^^^^^^^^
pub struct ConstantOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// ConstantPathAndWriteNode represents the use of the `&&=` operator for assignment to a constant path.
//
//     Parent::Child &&= value
//     ^^^^^^^^^^^^^^^^^^^^^^^
pub struct ConstantPathAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	target       Node
	operator_loc Location
	value        Node
}

// ConstantPathNode represents accessing a constant through a path of `::` operators.
//
//     Foo::Bar
//     ^^^^^^^^
pub struct ConstantPathNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The left-hand node of the path, if present. It can be `nil` or any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression). It will be `nil` when the constant lookup is at the root of the module tree.
	//
	//     Foo::Bar
	//     ^^^
	//
	//     self::Test
	//     ^^^^
	//
	//     a.b::C
	//     ^^^
	parent ?Node

	// The name of the constant being accessed. This could be `nil` in the event of a syntax error.
	name ?ConstantId

	// The location of the `::` delimiter.
	//
	//     ::Foo
	//     ^^
	//
	//     One::Two
	//        ^^
	delimiter_loc Location

	// The location of the name of the constant.
	//
	//     ::Foo
	//       ^^^
	//
	//     One::Two
	//          ^^^
	name_loc Location
}

// ConstantPathOperatorWriteNode represents assigning to a constant path using an operator that isn't `=`.
//
//     Parent::Child += value
//     ^^^^^^^^^^^^^^^^^^^^^^
pub struct ConstantPathOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	target              Node
	binary_operator_loc Location
	value               Node
	binary_operator     ConstantId
}

// ConstantPathOrWriteNode represents the use of the `||=` operator for assignment to a constant path.
//
//     Parent::Child ||= value
//     ^^^^^^^^^^^^^^^^^^^^^^^
pub struct ConstantPathOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	target       Node
	operator_loc Location
	value        Node
}

// ConstantPathTargetNode represents writing to a constant path in a context that doesn't have an explicit value.
//
//     Foo::Foo, Bar::Bar = baz
//     ^^^^^^^^  ^^^^^^^^
pub struct ConstantPathTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	parent        ?Node
	name          ?ConstantId
	delimiter_loc Location
	name_loc      Location
}

// ConstantPathWriteNode represents writing to a constant path.
//
//     ::Foo = 1
//     ^^^^^^^^^
//
//     Foo::Bar = 1
//     ^^^^^^^^^^^^
//
//     ::Foo::Bar = 1
//     ^^^^^^^^^^^^^^
pub struct ConstantPathWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// A node representing the constant path being written to.
	//
	//     Foo::Bar = 1
	//     ^^^^^^^^
	//
	//     ::Foo = :abc
	//     ^^^^^
	target Node

	// The location of the `=` operator.
	//
	//     ::ABC = 123
	//           ^
	operator_loc Location

	// The value to write to the constant path. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     FOO::BAR = :abc
	//                ^^^^
	value Node
}

// ConstantReadNode represents referencing a constant.
//
//     Foo
//     ^^^
pub struct ConstantReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the [constant](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#constants).
	//
	//     X              # name `:X`
	//
	//     SOME_CONSTANT  # name `:SOME_CONSTANT`
	name ConstantId
}

// ConstantTargetNode represents writing to a constant in a context that doesn't have an explicit value.
//
//     Foo, Bar = baz
//     ^^^  ^^^
pub struct ConstantTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name ConstantId
}

// ConstantWriteNode represents writing to a constant.
//
//     Foo = 1
//     ^^^^^^^
pub struct ConstantWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the [constant](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#constants).
	//
	//     Foo = :bar # name `:Foo`
	//
	//     XYZ = 1    # name `:XYZ`
	name ConstantId

	// The location of the constant name.
	//
	//     FOO = 1
	//     ^^^
	name_loc Location

	// The value to write to the constant. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     FOO = :bar
	//           ^^^^
	//
	//     MyClass = Class.new
	//               ^^^^^^^^^
	value Node

	// The location of the `=` operator.
	//
	//     FOO = :bar
	//         ^
	operator_loc Location
}

// DefNode represents a method definition.
//
//     def method
//     end
//     ^^^^^^^^^^
pub struct DefNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name            ConstantId
	name_loc        Location
	receiver        ?Node
	parameters      ?Node
	body            ?Node
	locals          []ConstantId
	def_keyword_loc Location
	operator_loc    ?Location
	lparen_loc      ?Location
	rparen_loc      ?Location
	equal_loc       ?Location
	end_keyword_loc ?Location
}

// DefinedNode represents the use of the `defined?` keyword.
//
//     defined?(a)
//     ^^^^^^^^^^^
pub struct DefinedNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	lparen_loc  ?Location
	value       Node
	rparen_loc  ?Location
	keyword_loc Location
}

// ElseNode represents an `else` clause in a `case`, `if`, or `unless` statement.
//
//     if a then b else c end
//                 ^^^^^^^^^^
pub struct ElseNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	else_keyword_loc Location
	statements       ?Node
	end_keyword_loc  ?Location
}

// EmbeddedStatementsNode represents an interpolated set of statements.
//
//     "foo #{bar}"
//          ^^^^^^
pub struct EmbeddedStatementsNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	statements  ?Node
	closing_loc Location
}

// EmbeddedVariableNode represents an interpolated variable.
//
//     "foo #@bar"
//          ^^^^^
pub struct EmbeddedVariableNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	operator_loc Location
	variable     Node
}

// EnsureNode represents an `ensure` clause in a `begin` statement.
//
//     begin
//       foo
//     ensure
//     ^^^^^^
//       bar
//     end
pub struct EnsureNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	ensure_keyword_loc Location
	statements         ?Node
	end_keyword_loc    Location
}

// FalseNode represents the use of the literal `false` keyword.
//
//     false
//     ^^^^^
pub struct FalseNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// FindPatternNode represents a find pattern in pattern matching.
//
//     foo in *bar, baz, *qux
//            ^^^^^^^^^^^^^^^
//
//     foo in [*bar, baz, *qux]
//            ^^^^^^^^^^^^^^^^^
//
//     foo in Foo(*bar, baz, *qux)
//            ^^^^^^^^^^^^^^^^^^^^
//
//     foo => *bar, baz, *qux
//            ^^^^^^^^^^^^^^^
pub struct FindPatternNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the optional constant preceding the pattern
	//
	//     foo in Foo(*bar, baz, *qux)
	//            ^^^
	constant ?Node

	// Represents the first wildcard node in the pattern.
	//
	//     foo in *bar, baz, *qux
	//            ^^^^
	//
	//     foo in Foo(*bar, baz, *qux)
	//                ^^^^
	left Node

	// Represents the nodes in between the wildcards.
	//
	//     foo in *bar, baz, *qux
	//                  ^^^
	//
	//     foo in Foo(*bar, baz, 1, *qux)
	//                      ^^^^^^
	requireds []Node

	// Represents the second wildcard node in the pattern.
	//
	//     foo in *bar, baz, *qux
	//                       ^^^^
	//
	//     foo in Foo(*bar, baz, *qux)
	//                           ^^^^
	right Node

	// The location of the opening brace.
	//
	//     foo in [*bar, baz, *qux]
	//            ^
	//
	//     foo in Foo(*bar, baz, *qux)
	//               ^
	opening_loc ?Location

	// The location of the closing brace.
	//
	//     foo in [*bar, baz, *qux]
	//                            ^
	//
	//     foo in Foo(*bar, baz, *qux)
	//                               ^
	closing_loc ?Location
}

// FlipFlopNode represents the use of the `..` or `...` operators to create flip flops.
//
//     baz if foo .. bar
//            ^^^^^^^^^^
pub struct FlipFlopNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	left         ?Node
	right        ?Node
	operator_loc Location
}

// FloatNode represents a floating point number literal.
//
//     1.0
//     ^^^
pub struct FloatNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The value of the floating point number as a Float.
	value f64
}

// ForNode represents the use of the `for` keyword.
//
//     for i in a end
//     ^^^^^^^^^^^^^^
pub struct ForNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The index expression for `for` loops.
	//
	//     for i in a end
	//         ^
	index Node

	// The collection to iterate over.
	//
	//     for i in a end
	//              ^
	collection Node

	// Represents the body of statements to execute for each iteration of the loop.
	//
	//     for i in a
	//       foo(i)
	//       ^^^^^^
	//     end
	statements ?Node

	// The location of the `for` keyword.
	//
	//     for i in a end
	//     ^^^
	for_keyword_loc Location

	// The location of the `in` keyword.
	//
	//     for i in a end
	//           ^^
	in_keyword_loc Location

	// The location of the `do` keyword, if present.
	//
	//     for i in a do end
	//                ^^
	do_keyword_loc ?Location

	// The location of the `end` keyword.
	//
	//     for i in a end
	//                ^^^
	end_keyword_loc Location
}

// ForwardingArgumentsNode represents forwarding all arguments to this method to another method.
//
//     def foo(...)
//       bar(...)
//           ^^^
//     end
pub struct ForwardingArgumentsNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// ForwardingParameterNode represents the use of the forwarding parameter in a method, block, or lambda declaration.
//
//     def foo(...)
//             ^^^
//     end
pub struct ForwardingParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// ForwardingSuperNode represents the use of the `super` keyword without parentheses or arguments, but which might have a block.
//
//     super
//     ^^^^^
//
//     super { 123 }
//     ^^^^^^^^^^^^^
//
// If it has any other arguments, it would be a `SuperNode` instead.
pub struct ForwardingSuperNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// All other arguments are forwarded as normal, except the original block is replaced with the new block.
	block ?Node
}

// GlobalVariableAndWriteNode represents the use of the `&&=` operator for assignment to a global variable.
//
//     $target &&= value
//     ^^^^^^^^^^^^^^^^^
pub struct GlobalVariableAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// GlobalVariableOperatorWriteNode represents assigning to a global variable using an operator that isn't `=`.
//
//     $target += value
//     ^^^^^^^^^^^^^^^^
pub struct GlobalVariableOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name                ConstantId
	name_loc            Location
	binary_operator_loc Location
	value               Node
	binary_operator     ConstantId
}

// GlobalVariableOrWriteNode represents the use of the `||=` operator for assignment to a global variable.
//
//     $target ||= value
//     ^^^^^^^^^^^^^^^^^
pub struct GlobalVariableOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// GlobalVariableReadNode represents referencing a global variable.
//
//     $foo
//     ^^^^
pub struct GlobalVariableReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the global variable, which is a `$` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifier). Alternatively, it can be one of the special global variables designated by a symbol.
	//
	//     $foo   # name `:$foo`
	//
	//     $_Test # name `:$_Test`
	name ConstantId
}

// GlobalVariableTargetNode represents writing to a global variable in a context that doesn't have an explicit value.
//
//     $foo, $bar = baz
//     ^^^^  ^^^^
pub struct GlobalVariableTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name ConstantId
}

// GlobalVariableWriteNode represents writing to a global variable.
//
//     $foo = 1
//     ^^^^^^^^
pub struct GlobalVariableWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the global variable, which is a `$` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifier). Alternatively, it can be one of the special global variables designated by a symbol.
	//
	//     $foo = :bar  # name `:$foo`
	//
	//     $_Test = 123 # name `:$_Test`
	name ConstantId

	// The location of the global variable's name.
	//
	//     $foo = :bar
	//     ^^^^
	name_loc Location

	// The value to write to the global variable. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     $foo = :bar
	//            ^^^^
	//
	//     $-xyz = 123
	//             ^^^
	value Node

	// The location of the `=` operator.
	//
	//     $foo = :bar
	//          ^
	operator_loc Location
}

// HashNode represents a hash literal.
//
//     { a => b }
//     ^^^^^^^^^^
pub struct HashNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The location of the opening brace.
	//
	//     { a => b }
	//     ^
	opening_loc Location

	// The elements of the hash. These can be either `AssocNode`s or `AssocSplatNode`s.
	//
	//     { a: b }
	//       ^^^^
	//
	//     { **foo }
	//       ^^^^^
	elements []Node

	// The location of the closing brace.
	//
	//     { a => b }
	//              ^
	closing_loc Location
}

// HashPatternNode represents a hash pattern in pattern matching.
//
//     foo => { a: 1, b: 2 }
//            ^^^^^^^^^^^^^^
//
//     foo => { a: 1, b: 2, **c }
//            ^^^^^^^^^^^^^^^^^^^
//
//     foo => Bar[a: 1, b: 2]
//            ^^^^^^^^^^^^^^^
//
//     foo in { a: 1, b: 2 }
//            ^^^^^^^^^^^^^^
pub struct HashPatternNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the optional constant preceding the Hash.
	//
	//     foo => Bar[a: 1, b: 2]
	//          ^^^
	//
	//     foo => Bar::Baz[a: 1, b: 2]
	//          ^^^^^^^^
	constant ?Node

	// Represents the explicit named hash keys and values.
	//
	//     foo => { a: 1, b:, ** }
	//              ^^^^^^^^
	elements []Node

	// Represents the rest of the Hash keys and values. This can be named, unnamed, or explicitly forbidden via `**nil`, this last one results in a `NoKeywordsParameterNode`.
	//
	//     foo => { a: 1, b:, **c }
	//                        ^^^
	//
	//     foo => { a: 1, b:, ** }
	//                        ^^
	//
	//     foo => { a: 1, b:, **nil }
	//                        ^^^^^
	rest ?Node

	// The location of the opening brace.
	//
	//     foo => { a: 1 }
	//            ^
	//
	//     foo => Bar[a: 1]
	//               ^
	opening_loc ?Location

	// The location of the closing brace.
	//
	//     foo => { a: 1 }
	//                   ^
	//
	//     foo => Bar[a: 1]
	//                    ^
	closing_loc ?Location
}

// IfNode represents the use of the `if` keyword, either in the block form or the modifier form, or a ternary expression.
//
//     bar if foo
//     ^^^^^^^^^^
//
//     if foo then bar end
//     ^^^^^^^^^^^^^^^^^^^
//
//     foo ? bar : baz
//     ^^^^^^^^^^^^^^^
pub struct IfNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The location of the `if` keyword if present.
	//
	//     bar if foo
	//         ^^
	//
	// The `if_keyword_loc` field will be `nil` when the `IfNode` represents a ternary expression.
	if_keyword_loc ?Location

	// The node for the condition the `IfNode` is testing.
	//
	//     if foo
	//        ^^^
	//       bar
	//     end
	//
	//     bar if foo
	//            ^^^
	//
	//     foo ? bar : baz
	//     ^^^
	predicate Node

	// The location of the `then` keyword (if present) or the `?` in a ternary expression, `nil` otherwise.
	//
	//     if foo then bar end
	//            ^^^^
	//
	//     a ? b : c
	//       ^
	then_keyword_loc ?Location

	// Represents the body of statements that will be executed when the predicate is evaluated as truthy. Will be `nil` when no body is provided.
	//
	//     if foo
	//       bar
	//       ^^^
	//       baz
	//       ^^^
	//     end
	statements ?Node

	// Represents an `ElseNode` or an `IfNode` when there is an `else` or an `elsif` in the `if` statement.
	//
	//     if foo
	//       bar
	//     elsif baz
	//     ^^^^^^^^^
	//       qux
	//       ^^^
	//     end
	//     ^^^
	//
	//     if foo then bar else baz end
	//                     ^^^^^^^^^^^^
	subsequent ?Node

	// The location of the `end` keyword if present, `nil` otherwise.
	//
	//     if foo
	//       bar
	//     end
	//     ^^^
	end_keyword_loc ?Location
}

// ImaginaryNode represents an imaginary number literal.
//
//     1.0i
//     ^^^^
pub struct ImaginaryNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	numeric Node
}

// ImplicitNode represents a node that is implicitly being added to the tree but doesn't correspond directly to a node in the source.
//
//     { foo: }
//       ^^^^
//
//     { Foo: }
//       ^^^^
//
//     foo in { bar: }
//              ^^^^
pub struct ImplicitNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	value Node
}

// ImplicitRestNode represents using a trailing comma to indicate an implicit rest parameter.
//
//     foo { |bar,| }
//               ^
//
//     foo in [bar,]
//                ^
//
//     for foo, in bar do end
//            ^
//
//     foo, = bar
//        ^
pub struct ImplicitRestNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// InNode represents the use of the `in` keyword in a case statement.
//
//     case a; in b then c end
//             ^^^^^^^^^^^
pub struct InNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	pattern    Node
	statements ?Node
	in_loc     Location
	then_loc   ?Location
}

// IndexAndWriteNode represents the use of the `&&=` operator on a call to the `[]` method.
//
//     foo.bar[baz] &&= value
//     ^^^^^^^^^^^^^^^^^^^^^^
pub struct IndexAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	receiver          ?Node
	call_operator_loc ?Location
	opening_loc       Location
	arguments         ?Node
	closing_loc       Location
	block             ?Node
	operator_loc      Location
	value             Node
}

// IndexOperatorWriteNode represents the use of an assignment operator on a call to `[]`.
//
//     foo.bar[baz] += value
//     ^^^^^^^^^^^^^^^^^^^^^
pub struct IndexOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	receiver            ?Node
	call_operator_loc   ?Location
	opening_loc         Location
	arguments           ?Node
	closing_loc         Location
	block               ?Node
	binary_operator     ConstantId
	binary_operator_loc Location
	value               Node
}

// IndexOrWriteNode represents the use of the `||=` operator on a call to `[]`.
//
//     foo.bar[baz] ||= value
//     ^^^^^^^^^^^^^^^^^^^^^^
pub struct IndexOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	receiver          ?Node
	call_operator_loc ?Location
	opening_loc       Location
	arguments         ?Node
	closing_loc       Location
	block             ?Node
	operator_loc      Location
	value             Node
}

// IndexTargetNode represents assigning to an index.
//
//     foo[bar], = 1
//     ^^^^^^^^
//
//     begin
//     rescue => foo[bar]
//               ^^^^^^^^
//     end
//
//     for foo[bar] in baz do end
//         ^^^^^^^^
pub struct IndexTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	receiver    Node
	opening_loc Location
	arguments   ?Node
	closing_loc Location
	block       ?Node
}

// InstanceVariableAndWriteNode represents the use of the `&&=` operator for assignment to an instance variable.
//
//     @target &&= value
//     ^^^^^^^^^^^^^^^^^
pub struct InstanceVariableAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// InstanceVariableOperatorWriteNode represents assigning to an instance variable using an operator that isn't `=`.
//
//     @target += value
//     ^^^^^^^^^^^^^^^^
pub struct InstanceVariableOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name                ConstantId
	name_loc            Location
	binary_operator_loc Location
	value               Node
	binary_operator     ConstantId
}

// InstanceVariableOrWriteNode represents the use of the `||=` operator for assignment to an instance variable.
//
//     @target ||= value
//     ^^^^^^^^^^^^^^^^^
pub struct InstanceVariableOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// InstanceVariableReadNode represents referencing an instance variable.
//
//     @foo
//     ^^^^
pub struct InstanceVariableReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the instance variable, which is a `@` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     @x     # name `:@x`
	//
	//     @_test # name `:@_test`
	name ConstantId
}

// InstanceVariableTargetNode represents writing to an instance variable in a context that doesn't have an explicit value.
//
//     @foo, @bar = baz
//     ^^^^  ^^^^
pub struct InstanceVariableTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name ConstantId
}

// InstanceVariableWriteNode represents writing to an instance variable.
//
//     @foo = 1
//     ^^^^^^^^
pub struct InstanceVariableWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the instance variable, which is a `@` followed by an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     @x = :y       # name `:@x`
	//
	//     @_foo = "bar" # name `@_foo`
	name ConstantId

	// The location of the variable name.
	//
	//     @_x = 1
	//     ^^^
	name_loc Location

	// The value to write to the instance variable. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     @foo = :bar
	//            ^^^^
	//
	//     @_x = 1234
	//           ^^^^
	value Node

	// The location of the `=` operator.
	//
	//     @x = y
	//        ^
	operator_loc Location
}

// IntegerNode represents an integer number literal.
//
//     1
//     ^
pub struct IntegerNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The value of the integer literal as a number.
	value Integer
}

// InterpolatedMatchLastLineNode represents a regular expression literal that contains interpolation that is being used in the predicate of a conditional to implicitly match against the last line read by an IO object.
//
//     if /foo #{bar} baz/ then end
//        ^^^^^^^^^^^^^^^^
pub struct InterpolatedMatchLastLineNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	parts       []Node
	closing_loc Location
}

// InterpolatedRegularExpressionNode represents a regular expression literal that contains interpolation.
//
//     /foo #{bar} baz/
//     ^^^^^^^^^^^^^^^^
pub struct InterpolatedRegularExpressionNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	parts       []Node
	closing_loc Location
}

// InterpolatedStringNode represents a string literal that contains interpolation.
//
//     "foo #{bar} baz"
//     ^^^^^^^^^^^^^^^^
pub struct InterpolatedStringNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc ?Location
	parts       []Node
	closing_loc ?Location
}

// InterpolatedSymbolNode represents a symbol literal that contains interpolation.
//
//     :"foo #{bar} baz"
//     ^^^^^^^^^^^^^^^^^
pub struct InterpolatedSymbolNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc ?Location
	parts       []Node
	closing_loc ?Location
}

// InterpolatedXStringNode represents an xstring literal that contains interpolation.
//
//     `foo #{bar} baz`
//     ^^^^^^^^^^^^^^^^
pub struct InterpolatedXStringNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	parts       []Node
	closing_loc Location
}

// ItLocalVariableReadNode represents reading from the implicit `it` local variable.
//
//     -> { it }
//          ^^
pub struct ItLocalVariableReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// ItParametersNode represents an implicit set of parameters through the use of the `it` keyword within a block or lambda.
//
//     -> { it + it }
//     ^^^^^^^^^^^^^^
pub struct ItParametersNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// KeywordHashNode represents a hash literal without opening and closing braces.
//
//     foo(a: b)
//         ^^^^
pub struct KeywordHashNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	elements []Node
}

// KeywordRestParameterNode represents a keyword rest parameter to a method, block, or lambda definition.
//
//     def a(**b)
//           ^^^
//     end
pub struct KeywordRestParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ?ConstantId
	name_loc     ?Location
	operator_loc Location
}

// LambdaNode represents using a lambda literal (not the lambda method call).
//
//     ->(value) { value * 2 }
//     ^^^^^^^^^^^^^^^^^^^^^^^
pub struct LambdaNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	locals       []ConstantId
	operator_loc Location
	opening_loc  Location
	closing_loc  Location
	parameters   ?Node
	body         ?Node
}

// LocalVariableAndWriteNode represents the use of the `&&=` operator for assignment to a local variable.
//
//     target &&= value
//     ^^^^^^^^^^^^^^^^
pub struct LocalVariableAndWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name_loc     Location
	operator_loc Location
	value        Node
	name         ConstantId
	depth        u32
}

// LocalVariableOperatorWriteNode represents assigning to a local variable using an operator that isn't `=`.
//
//     target += value
//     ^^^^^^^^^^^^^^^
pub struct LocalVariableOperatorWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name_loc            Location
	binary_operator_loc Location
	value               Node
	name                ConstantId
	binary_operator     ConstantId
	depth               u32
}

// LocalVariableOrWriteNode represents the use of the `||=` operator for assignment to a local variable.
//
//     target ||= value
//     ^^^^^^^^^^^^^^^^
pub struct LocalVariableOrWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name_loc     Location
	operator_loc Location
	value        Node
	name         ConstantId
	depth        u32
}

// LocalVariableReadNode represents reading a local variable. Note that this requires that a local variable of the same name has already been written to in the same scope, otherwise it is parsed as a method call.
//
//     foo
//     ^^^
pub struct LocalVariableReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the local variable, which is an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     x      # name `:x`
	//
	//     _Test  # name `:_Test`
	//
	// Note that this can also be an underscore followed by a number for the default block parameters.
	//
	//     _1     # name `:_1`
	name ConstantId

	// The number of visible scopes that should be searched to find the origin of this local variable.
	//
	//     foo = 1; foo # depth 0
	//
	//     bar = 2; tap { bar } # depth 1
	//
	// The specific rules for calculating the depth may differ from individual Ruby implementations, as they are not specified by the language. For more information, see [the Prism documentation](https://github.com/ruby/prism/blob/main/docs/local_variable_depth.md).
	depth u32
}

// LocalVariableTargetNode represents writing to a local variable in a context that doesn't have an explicit value.
//
//     foo, bar = baz
//     ^^^  ^^^
//
//     foo => baz
//            ^^^
pub struct LocalVariableTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name  ConstantId
	depth u32
}

// LocalVariableWriteNode represents writing to a local variable.
//
//     foo = 1
//     ^^^^^^^
pub struct LocalVariableWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The name of the local variable, which is an [identifier](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#identifiers).
	//
	//     foo = :bar # name `:foo`
	//
	//     abc = 123  # name `:abc`
	name ConstantId

	// The number of semantic scopes we have to traverse to find the declaration of this variable.
	//
	//     foo = 1         # depth 0
	//
	//     tap { foo = 1 } # depth 1
	//
	// The specific rules for calculating the depth may differ from individual Ruby implementations, as they are not specified by the language. For more information, see [the Prism documentation](https://github.com/ruby/prism/blob/main/docs/local_variable_depth.md).
	depth u32

	// The location of the variable name.
	//
	//     foo = :bar
	//     ^^^
	name_loc Location

	// The value to write to the local variable. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     foo = :bar
	//           ^^^^
	//
	//     abc = 1234
	//           ^^^^
	//
	// Note that since the name of a local variable is known before the value is parsed, it is valid for a local variable to appear within the value of its own write.
	//
	//     foo = foo
	value Node

	// The location of the `=` operator.
	//
	//     x = :y
	//       ^
	operator_loc Location
}

// MatchLastLineNode represents a regular expression literal used in the predicate of a conditional to implicitly match against the last line read by an IO object.
//
//     if /foo/i then end
//        ^^^^^^
pub struct MatchLastLineNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	content_loc Location
	closing_loc Location
	unescaped   string
}

// MatchPredicateNode represents the use of the modifier `in` operator.
//
//     foo in bar
//     ^^^^^^^^^^
pub struct MatchPredicateNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	value        Node
	pattern      Node
	operator_loc Location
}

// MatchRequiredNode represents the use of the `=>` operator.
//
//     foo => bar
//     ^^^^^^^^^^
pub struct MatchRequiredNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the left-hand side of the operator.
	//
	//     foo => bar
	//     ^^^
	value Node

	// Represents the right-hand side of the operator. The type of the node depends on the expression.
	//
	// Anything that looks like a local variable name (including `_`) will result in a `LocalVariableTargetNode`.
	//
	//     foo => a # This is equivalent to writing `a = foo`
	//            ^
	//
	// Using an explicit `Array` or combining expressions with `,` will result in a `ArrayPatternNode`. This can be preceded by a constant.
	//
	//     foo => [a]
	//            ^^^
	//
	//     foo => a, b
	//            ^^^^
	//
	//     foo => Bar[a, b]
	//            ^^^^^^^^^
	//
	// If the array pattern contains at least two wildcard matches, a `FindPatternNode` is created instead.
	//
	//     foo => *, 1, *a
	//            ^^^^^
	//
	// Using an explicit `Hash` or a constant with square brackets and hash keys in the square brackets will result in a `HashPatternNode`.
	//
	//     foo => { a: 1, b: }
	//
	//     foo => Bar[a: 1, b:]
	//
	//     foo => Bar[**]
	//
	// To use any variable that needs run time evaluation, pinning is required. This results in a `PinnedVariableNode`
	//
	//     foo => ^a
	//            ^^
	//
	// Similar, any expression can be used with pinning. This results in a `PinnedExpressionNode`.
	//
	//     foo => ^(a + 1)
	//
	// Anything else will result in the regular node for that expression, for example a `ConstantReadNode`.
	//
	//     foo => CONST
	pattern Node

	// The location of the operator.
	//
	//     foo => bar
	//         ^^
	operator_loc Location
}

// MatchWriteNode represents writing local variables using a regular expression match with named capture groups.
//
//     /(?<foo>bar)/ =~ baz
//     ^^^^^^^^^^^^^^^^^^^^
pub struct MatchWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	call    Node
	targets []Node
}

// MissingNode represents a node that is missing from the source and results in a syntax error.
pub struct MissingNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// ModuleNode represents a module declaration involving the `module` keyword.
//
//     module Foo end
//     ^^^^^^^^^^^^^^
pub struct ModuleNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	locals             []ConstantId
	module_keyword_loc Location
	constant_path      Node
	body               ?Node
	end_keyword_loc    Location
	name               ConstantId
}

// MultiTargetNode represents a multi-target expression.
//
//     a, (b, c) = 1, 2, 3
//        ^^^^^^
//
// This can be a part of `MultiWriteNode` as above, or the target of a `for` loop
//
//     for a, b in [[1, 2], [3, 4]]
//         ^^^^
pub struct MultiTargetNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the targets expressions before a splat node.
	//
	//     a, (b, c, *) = 1, 2, 3, 4, 5
	//         ^^^^
	//
	// The splat node can be absent, in that case all target expressions are in the left field.
	//
	//     a, (b, c) = 1, 2, 3, 4, 5
	//         ^^^^
	lefts []Node

	// Represents a splat node in the target expression.
	//
	//     a, (b, *c) = 1, 2, 3, 4
	//            ^^
	//
	// The variable can be empty, this results in a `SplatNode` with a `nil` expression field.
	//
	//     a, (b, *) = 1, 2, 3, 4
	//            ^
	//
	// If the `*` is omitted, this field will contain an `ImplicitRestNode`
	//
	//     a, (b,) = 1, 2, 3, 4
	//          ^
	rest ?Node

	// Represents the targets expressions after a splat node.
	//
	//     a, (*, b, c) = 1, 2, 3, 4, 5
	//            ^^^^
	rights []Node

	// The location of the opening parenthesis.
	//
	//     a, (b, c) = 1, 2, 3
	//        ^
	lparen_loc ?Location

	// The location of the closing parenthesis.
	//
	//     a, (b, c) = 1, 2, 3
	//             ^
	rparen_loc ?Location
}

// MultiWriteNode represents a write to a multi-target expression.
//
//     a, b, c = 1, 2, 3
//     ^^^^^^^^^^^^^^^^^
pub struct MultiWriteNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the targets expressions before a splat node.
	//
	//     a, b, * = 1, 2, 3, 4, 5
	//     ^^^^
	//
	// The splat node can be absent, in that case all target expressions are in the left field.
	//
	//     a, b, c = 1, 2, 3, 4, 5
	//     ^^^^^^^
	lefts []Node

	// Represents a splat node in the target expression.
	//
	//     a, b, *c = 1, 2, 3, 4
	//           ^^
	//
	// The variable can be empty, this results in a `SplatNode` with a `nil` expression field.
	//
	//     a, b, * = 1, 2, 3, 4
	//           ^
	//
	// If the `*` is omitted, this field will contain an `ImplicitRestNode`
	//
	//     a, b, = 1, 2, 3, 4
	//         ^
	rest ?Node

	// Represents the targets expressions after a splat node.
	//
	//     a, *, b, c = 1, 2, 3, 4, 5
	//           ^^^^
	rights []Node

	// The location of the opening parenthesis.
	//
	//     (a, b, c) = 1, 2, 3
	//     ^
	lparen_loc ?Location

	// The location of the closing parenthesis.
	//
	//     (a, b, c) = 1, 2, 3
	//             ^
	rparen_loc ?Location

	// The location of the operator.
	//
	//     a, b, c = 1, 2, 3
	//             ^
	operator_loc Location

	// The value to write to the targets. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     a, b, c = 1, 2, 3
	//               ^^^^^^^
	value Node
}

// NextNode represents the use of the `next` keyword.
//
//     next 1
//     ^^^^^^
pub struct NextNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	arguments   ?Node
	keyword_loc Location
}

// NilNode represents the use of the `nil` keyword.
//
//     nil
//     ^^^
pub struct NilNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// NoKeywordsParameterNode represents the use of `**nil` inside method arguments.
//
//     def a(**nil)
//           ^^^^^
//     end
pub struct NoKeywordsParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	operator_loc Location
	keyword_loc  Location
}

// NumberedParametersNode represents an implicit set of parameters through the use of numbered parameters within a block or lambda.
//
//     -> { _1 + _2 }
//     ^^^^^^^^^^^^^^
pub struct NumberedParametersNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	maximum u8
}

// NumberedReferenceReadNode represents reading a numbered reference to a capture in the previous match.
//
//     $1
//     ^^
pub struct NumberedReferenceReadNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The (1-indexed, from the left) number of the capture group. Numbered references that are too large result in this value being `0`.
	//
	//     $1          # number `1`
	//
	//     $5432       # number `5432`
	//
	//     $4294967296 # number `0`
	number u32
}

// OptionalKeywordParameterNode represents an optional keyword parameter to a method, block, or lambda definition.
//
//     def a(b: 1)
//           ^^^^
//     end
pub struct OptionalKeywordParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name     ConstantId
	name_loc Location
	value    Node
}

// OptionalParameterNode represents an optional parameter to a method, block, or lambda definition.
//
//     def a(b = 1)
//           ^^^^^
//     end
pub struct OptionalParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ConstantId
	name_loc     Location
	operator_loc Location
	value        Node
}

// OrNode represents the use of the `||` operator or the `or` keyword.
//
//     left or right
//     ^^^^^^^^^^^^^
pub struct OrNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the left side of the expression. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     left or right
	//     ^^^^
	//
	//     1 || 2
	//     ^
	left Node

	// Represents the right side of the expression.
	//
	//     left || right
	//             ^^^^^
	//
	//     1 or 2
	//          ^
	right Node

	// The location of the `or` keyword or the `||` operator.
	//
	//     left or right
	//          ^^
	operator_loc Location
}

// ParametersNode represents the list of parameters on a method, block, or lambda definition.
//
//     def a(b, c, d)
//           ^^^^^^^
//     end
pub struct ParametersNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	requireds    []Node
	optionals    []Node
	rest         ?Node
	posts        []Node
	keywords     []Node
	keyword_rest ?Node
	block        ?Node
}

// ParenthesesNode represents a parenthesized expression
//
//     (10 + 34)
//     ^^^^^^^^^
pub struct ParenthesesNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	body        ?Node
	opening_loc Location
	closing_loc Location
}

// PinnedExpressionNode represents the use of the `^` operator for pinning an expression in a pattern matching expression.
//
//     foo in ^(bar)
//            ^^^^^^
pub struct PinnedExpressionNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The expression used in the pinned expression
	//
	//     foo in ^(bar)
	//              ^^^
	expression Node

	// The location of the `^` operator
	//
	//     foo in ^(bar)
	//            ^
	operator_loc Location

	// The location of the opening parenthesis.
	//
	//     foo in ^(bar)
	//             ^
	lparen_loc Location

	// The location of the closing parenthesis.
	//
	//     foo in ^(bar)
	//                 ^
	rparen_loc Location
}

// PinnedVariableNode represents the use of the `^` operator for pinning a variable in a pattern matching expression.
//
//     foo in ^bar
//            ^^^^
pub struct PinnedVariableNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The variable used in the pinned expression
	//
	//     foo in ^bar
	//             ^^^
	variable Node

	// The location of the `^` operator
	//
	//     foo in ^bar
	//            ^
	operator_loc Location
}

// PostExecutionNode represents the use of the `END` keyword.
//
//     END { foo }
//     ^^^^^^^^^^^
pub struct PostExecutionNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	statements  ?Node
	keyword_loc Location
	opening_loc Location
	closing_loc Location
}

// PreExecutionNode represents the use of the `BEGIN` keyword.
//
//     BEGIN { foo }
//     ^^^^^^^^^^^^^
pub struct PreExecutionNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	statements  ?Node
	keyword_loc Location
	opening_loc Location
	closing_loc Location
}

// ProgramNode the top level node of any parse tree.
pub struct ProgramNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	locals     []ConstantId
	statements Node
}

// RangeNode represents the use of the `..` or `...` operators.
//
//     1..2
//     ^^^^
//
//     c if a =~ /left/ ... b =~ /right/
//          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pub struct RangeNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The left-hand side of the range, if present. It can be either `nil` or any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     1...
	//     ^
	//
	//     hello...goodbye
	//     ^^^^^
	left ?Node

	// The right-hand side of the range, if present. It can be either `nil` or any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     ..5
	//       ^
	//
	//     1...foo
	//         ^^^
	// If neither right-hand or left-hand side was included, this will be a MissingNode.
	right ?Node

	// The location of the `..` or `...` operator.
	operator_loc Location
}

// RationalNode represents a rational number literal.
//
//     1.0r
//     ^^^^
pub struct RationalNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The numerator of the rational number.
	//
	//     1.5r # numerator 3
	numerator Integer

	// The denominator of the rational number.
	//
	//     1.5r # denominator 2
	denominator Integer
}

// RedoNode represents the use of the `redo` keyword.
//
//     redo
//     ^^^^
pub struct RedoNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// RegularExpressionNode represents a regular expression literal with no interpolation.
//
//     /foo/i
//     ^^^^^^
pub struct RegularExpressionNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	content_loc Location
	closing_loc Location
	unescaped   string
}

// RequiredKeywordParameterNode represents a required keyword parameter to a method, block, or lambda definition.
//
//     def a(b: )
//           ^^
//     end
pub struct RequiredKeywordParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name     ConstantId
	name_loc Location
}

// RequiredParameterNode represents a required parameter to a method, block, or lambda definition.
//
//     def a(b)
//           ^
//     end
pub struct RequiredParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name ConstantId
}

// RescueModifierNode represents an expression modified with a rescue.
//
//     foo rescue nil
//     ^^^^^^^^^^^^^^
pub struct RescueModifierNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	expression        Node
	keyword_loc       Location
	rescue_expression Node
}

// RescueNode represents a rescue statement.
//
//     begin
//     rescue Foo, *splat, Bar => ex
//       foo
//     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//     end
//
// `Foo, *splat, Bar` are in the `exceptions` field. `ex` is in the `reference` field.
pub struct RescueNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc      Location
	exceptions       []Node
	operator_loc     ?Location
	reference        ?Node
	then_keyword_loc ?Location
	statements       ?Node
	subsequent       ?Node
}

// RestParameterNode represents a rest parameter to a method, block, or lambda definition.
//
//     def a(*b)
//           ^^
//     end
pub struct RestParameterNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	name         ?ConstantId
	name_loc     ?Location
	operator_loc Location
}

// RetryNode represents the use of the `retry` keyword.
//
//     retry
//     ^^^^^
pub struct RetryNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// ReturnNode represents the use of the `return` keyword.
//
//     return 1
//     ^^^^^^^^
pub struct ReturnNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc Location
	arguments   ?Node
}

// SelfNode represents the `self` keyword.
//
//     self
//     ^^^^
pub struct SelfNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// ShareableConstantNode this node wraps a constant write to indicate that when the value is written, it should have its shareability state modified.
//
//     # shareable_constant_value: literal
//     C = { a: 1 }
//     ^^^^^^^^^^^^
pub struct ShareableConstantNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The constant write that should be modified with the shareability state.
	write Node
}

// SingletonClassNode represents a singleton class declaration involving the `class` keyword.
//
//     class << self end
//     ^^^^^^^^^^^^^^^^^
pub struct SingletonClassNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	locals            []ConstantId
	class_keyword_loc Location
	operator_loc      Location
	expression        Node
	body              ?Node
	end_keyword_loc   Location
}

// SourceEncodingNode represents the use of the `__ENCODING__` keyword.
//
//     __ENCODING__
//     ^^^^^^^^^^^^
pub struct SourceEncodingNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// SourceFileNode represents the use of the `__FILE__` keyword.
//
//     __FILE__
//     ^^^^^^^^
pub struct SourceFileNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// Represents the file path being parsed. This corresponds directly to the `filepath` option given to the various `Prism::parse*` APIs.
	filepath string
}

// SourceLineNode represents the use of the `__LINE__` keyword.
//
//     __LINE__
//     ^^^^^^^^
pub struct SourceLineNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// SplatNode represents the use of the splat operator.
//
//     [*a]
//      ^^
pub struct SplatNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	operator_loc Location
	expression   ?Node
}

// StatementsNode represents a set of statements contained within some scope.
//
//     foo; bar; baz
//     ^^^^^^^^^^^^^
pub struct StatementsNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	body []Node
}

// StringNode represents a string literal, a string contained within a `%w` list, or plain string content within an interpolated string.
//
//     "foo"
//     ^^^^^
//
//     %w[foo]
//        ^^^
//
//     "foo #{bar} baz"
//      ^^^^      ^^^^
pub struct StringNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc ?Location
	content_loc Location
	closing_loc ?Location
	unescaped   string
}

// SuperNode represents the use of the `super` keyword with parentheses or arguments.
//
//     super()
//     ^^^^^^^
//
//     super foo, bar
//     ^^^^^^^^^^^^^^
//
// If no arguments are provided (except for a block), it would be a `ForwardingSuperNode` instead.
pub struct SuperNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc Location
	lparen_loc  ?Location

	// Can be only `nil` when there are empty parentheses, like `super()`.
	arguments ?Node

	rparen_loc ?Location
	block      ?Node
}

// SymbolNode represents a symbol literal or a symbol contained within a `%i` list.
//
//     :foo
//     ^^^^
//
//     %i[foo]
//        ^^^
pub struct SymbolNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc ?Location
	value_loc   ?Location
	closing_loc ?Location
	unescaped   string
}

// TrueNode represents the use of the literal `true` keyword.
//
//     true
//     ^^^^
pub struct TrueNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase
}

// UndefNode represents the use of the `undef` keyword.
//
//     undef :foo, :bar, :baz
//     ^^^^^^^^^^^^^^^^^^^^^^
pub struct UndefNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	names       []Node
	keyword_loc Location
}

// UnlessNode represents the use of the `unless` keyword, either in the block form or the modifier form.
//
//     bar unless foo
//     ^^^^^^^^^^^^^^
//
//     unless foo then bar end
//     ^^^^^^^^^^^^^^^^^^^^^^^
pub struct UnlessNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	// The location of the `unless` keyword.
	//
	//     unless cond then bar end
	//     ^^^^^^
	//
	//     bar unless cond
	//         ^^^^^^
	keyword_loc Location

	// The condition to be evaluated for the unless expression. It can be any [non-void expression](https://github.com/ruby/prism/blob/main/docs/parsing_rules.md#non-void-expression).
	//
	//     unless cond then bar end
	//            ^^^^
	//
	//     bar unless cond
	//                ^^^^
	predicate Node

	// The location of the `then` keyword, if present.
	//
	//     unless cond then bar end
	//                 ^^^^
	then_keyword_loc ?Location

	// The body of statements that will executed if the unless condition is
	// falsey. Will be `nil` if no body is provided.
	//
	//     unless cond then bar end
	//                      ^^^
	statements ?Node

	// The else clause of the unless expression, if present.
	//
	//     unless cond then bar else baz end
	//                          ^^^^^^^^
	else_clause ?Node

	// The location of the `end` keyword, if present.
	//
	//     unless cond then bar end
	//                          ^^^
	end_keyword_loc ?Location
}

// UntilNode represents the use of the `until` keyword, either in the block form or the modifier form.
//
//     bar until foo
//     ^^^^^^^^^^^^^
//
//     until foo do bar end
//     ^^^^^^^^^^^^^^^^^^^^
pub struct UntilNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc    Location
	do_keyword_loc ?Location
	closing_loc    ?Location
	predicate      Node
	statements     ?Node
}

// WhenNode represents the use of the `when` keyword within a case statement.
//
//     case true
//     when true
//     ^^^^^^^^^
//     end
pub struct WhenNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc      Location
	conditions       []Node
	then_keyword_loc ?Location
	statements       ?Node
}

// WhileNode represents the use of the `while` keyword, either in the block form or the modifier form.
//
//     bar while foo
//     ^^^^^^^^^^^^^
//
//     while foo do bar end
//     ^^^^^^^^^^^^^^^^^^^^
pub struct WhileNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc    Location
	do_keyword_loc ?Location
	closing_loc    ?Location
	predicate      Node
	statements     ?Node
}

// XStringNode represents an xstring literal with no interpolation.
//
//     `foo`
//     ^^^^^
pub struct XStringNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	opening_loc Location
	content_loc Location
	closing_loc Location
	unescaped   string
}

// YieldNode represents the use of the `yield` keyword.
//
//     yield 1
//     ^^^^^^^
pub struct YieldNode {
pub:
	// Base node metadata shared by all Prism AST nodes.
	base NodeBase

	keyword_loc Location
	lparen_loc  ?Location
	arguments   ?Node
	rparen_loc  ?Location
}
