// Code generated by tools/generate.v; DO NOT EDIT.
module serialize

// DiagnosticKind identifies a Prism parser diagnostic id.
pub enum DiagnosticKind {
	// PM_ERR_ALIAS_ARGUMENT
	err_alias_argument = 0
	// PM_ERR_ALIAS_ARGUMENT_NUMBERED_REFERENCE
	err_alias_argument_numbered_reference = 1
	// PM_ERR_AMPAMPEQ_MULTI_ASSIGN
	err_ampampeq_multi_assign = 2
	// PM_ERR_ARGUMENT_AFTER_BLOCK
	err_argument_after_block = 3
	// PM_ERR_ARGUMENT_AFTER_FORWARDING_ELLIPSES
	err_argument_after_forwarding_ellipses = 4
	// PM_ERR_ARGUMENT_BARE_HASH
	err_argument_bare_hash = 5
	// PM_ERR_ARGUMENT_BLOCK_FORWARDING
	err_argument_block_forwarding = 6
	// PM_ERR_ARGUMENT_BLOCK_MULTI
	err_argument_block_multi = 7
	// PM_ERR_ARGUMENT_CONFLICT_AMPERSAND
	err_argument_conflict_ampersand = 8
	// PM_ERR_ARGUMENT_CONFLICT_STAR
	err_argument_conflict_star = 9
	// PM_ERR_ARGUMENT_CONFLICT_STAR_STAR
	err_argument_conflict_star_star = 10
	// PM_ERR_ARGUMENT_FORMAL_CLASS
	err_argument_formal_class = 11
	// PM_ERR_ARGUMENT_FORMAL_CONSTANT
	err_argument_formal_constant = 12
	// PM_ERR_ARGUMENT_FORMAL_GLOBAL
	err_argument_formal_global = 13
	// PM_ERR_ARGUMENT_FORMAL_IVAR
	err_argument_formal_ivar = 14
	// PM_ERR_ARGUMENT_FORWARDING_UNBOUND
	err_argument_forwarding_unbound = 15
	// PM_ERR_ARGUMENT_NO_FORWARDING_AMPERSAND
	err_argument_no_forwarding_ampersand = 16
	// PM_ERR_ARGUMENT_NO_FORWARDING_ELLIPSES
	err_argument_no_forwarding_ellipses = 17
	// PM_ERR_ARGUMENT_NO_FORWARDING_STAR
	err_argument_no_forwarding_star = 18
	// PM_ERR_ARGUMENT_NO_FORWARDING_STAR_STAR
	err_argument_no_forwarding_star_star = 19
	// PM_ERR_ARGUMENT_SPLAT_AFTER_ASSOC_SPLAT
	err_argument_splat_after_assoc_splat = 20
	// PM_ERR_ARGUMENT_SPLAT_AFTER_SPLAT
	err_argument_splat_after_splat = 21
	// PM_ERR_ARGUMENT_TERM_PAREN
	err_argument_term_paren = 22
	// PM_ERR_ARGUMENT_UNEXPECTED_BLOCK
	err_argument_unexpected_block = 23
	// PM_ERR_ARRAY_ELEMENT
	err_array_element = 24
	// PM_ERR_ARRAY_EXPRESSION
	err_array_expression = 25
	// PM_ERR_ARRAY_EXPRESSION_AFTER_STAR
	err_array_expression_after_star = 26
	// PM_ERR_ARRAY_SEPARATOR
	err_array_separator = 27
	// PM_ERR_ARRAY_TERM
	err_array_term = 28
	// PM_ERR_BEGIN_LONELY_ELSE
	err_begin_lonely_else = 29
	// PM_ERR_BEGIN_TERM
	err_begin_term = 30
	// PM_ERR_BEGIN_UPCASE_BRACE
	err_begin_upcase_brace = 31
	// PM_ERR_BEGIN_UPCASE_TERM
	err_begin_upcase_term = 32
	// PM_ERR_BEGIN_UPCASE_TOPLEVEL
	err_begin_upcase_toplevel = 33
	// PM_ERR_BLOCK_PARAM_LOCAL_VARIABLE
	err_block_param_local_variable = 34
	// PM_ERR_BLOCK_PARAM_PIPE_TERM
	err_block_param_pipe_term = 35
	// PM_ERR_BLOCK_TERM_BRACE
	err_block_term_brace = 36
	// PM_ERR_BLOCK_TERM_END
	err_block_term_end = 37
	// PM_ERR_CANNOT_PARSE_EXPRESSION
	err_cannot_parse_expression = 38
	// PM_ERR_CANNOT_PARSE_STRING_PART
	err_cannot_parse_string_part = 39
	// PM_ERR_CASE_EXPRESSION_AFTER_CASE
	err_case_expression_after_case = 40
	// PM_ERR_CASE_EXPRESSION_AFTER_WHEN
	err_case_expression_after_when = 41
	// PM_ERR_CASE_MATCH_MISSING_PREDICATE
	err_case_match_missing_predicate = 42
	// PM_ERR_CASE_MISSING_CONDITIONS
	err_case_missing_conditions = 43
	// PM_ERR_CASE_TERM
	err_case_term = 44
	// PM_ERR_CLASS_IN_METHOD
	err_class_in_method = 45
	// PM_ERR_CLASS_NAME
	err_class_name = 46
	// PM_ERR_CLASS_SUPERCLASS
	err_class_superclass = 47
	// PM_ERR_CLASS_TERM
	err_class_term = 48
	// PM_ERR_CLASS_UNEXPECTED_END
	err_class_unexpected_end = 49
	// PM_ERR_CLASS_VARIABLE_BARE
	err_class_variable_bare = 50
	// PM_ERR_CONDITIONAL_ELSIF_PREDICATE
	err_conditional_elsif_predicate = 51
	// PM_ERR_CONDITIONAL_IF_PREDICATE
	err_conditional_if_predicate = 52
	// PM_ERR_CONDITIONAL_PREDICATE_TERM
	err_conditional_predicate_term = 53
	// PM_ERR_CONDITIONAL_TERM
	err_conditional_term = 54
	// PM_ERR_CONDITIONAL_TERM_ELSE
	err_conditional_term_else = 55
	// PM_ERR_CONDITIONAL_UNLESS_PREDICATE
	err_conditional_unless_predicate = 56
	// PM_ERR_CONDITIONAL_UNTIL_PREDICATE
	err_conditional_until_predicate = 57
	// PM_ERR_CONDITIONAL_WHILE_PREDICATE
	err_conditional_while_predicate = 58
	// PM_ERR_CONSTANT_PATH_COLON_COLON_CONSTANT
	err_constant_path_colon_colon_constant = 59
	// PM_ERR_DEF_ENDLESS
	err_def_endless = 60
	// PM_ERR_DEF_ENDLESS_PARAMETERS
	err_def_endless_parameters = 61
	// PM_ERR_DEF_ENDLESS_SETTER
	err_def_endless_setter = 62
	// PM_ERR_DEF_NAME
	err_def_name = 63
	// PM_ERR_DEF_PARAMS_TERM
	err_def_params_term = 64
	// PM_ERR_DEF_PARAMS_TERM_PAREN
	err_def_params_term_paren = 65
	// PM_ERR_DEF_RECEIVER
	err_def_receiver = 66
	// PM_ERR_DEF_RECEIVER_TERM
	err_def_receiver_term = 67
	// PM_ERR_DEF_TERM
	err_def_term = 68
	// PM_ERR_DEFINED_EXPRESSION
	err_defined_expression = 69
	// PM_ERR_EMBDOC_TERM
	err_embdoc_term = 70
	// PM_ERR_EMBEXPR_END
	err_embexpr_end = 71
	// PM_ERR_EMBVAR_INVALID
	err_embvar_invalid = 72
	// PM_ERR_END_UPCASE_BRACE
	err_end_upcase_brace = 73
	// PM_ERR_END_UPCASE_TERM
	err_end_upcase_term = 74
	// PM_ERR_ESCAPE_INVALID_CONTROL
	err_escape_invalid_control = 75
	// PM_ERR_ESCAPE_INVALID_CONTROL_REPEAT
	err_escape_invalid_control_repeat = 76
	// PM_ERR_ESCAPE_INVALID_HEXADECIMAL
	err_escape_invalid_hexadecimal = 77
	// PM_ERR_ESCAPE_INVALID_META
	err_escape_invalid_meta = 78
	// PM_ERR_ESCAPE_INVALID_META_REPEAT
	err_escape_invalid_meta_repeat = 79
	// PM_ERR_ESCAPE_INVALID_UNICODE
	err_escape_invalid_unicode = 80
	// PM_ERR_ESCAPE_INVALID_UNICODE_CM_FLAGS
	err_escape_invalid_unicode_cm_flags = 81
	// PM_ERR_ESCAPE_INVALID_UNICODE_LIST
	err_escape_invalid_unicode_list = 82
	// PM_ERR_ESCAPE_INVALID_UNICODE_LITERAL
	err_escape_invalid_unicode_literal = 83
	// PM_ERR_ESCAPE_INVALID_UNICODE_LONG
	err_escape_invalid_unicode_long = 84
	// PM_ERR_ESCAPE_INVALID_UNICODE_SHORT
	err_escape_invalid_unicode_short = 85
	// PM_ERR_ESCAPE_INVALID_UNICODE_TERM
	err_escape_invalid_unicode_term = 86
	// PM_ERR_EXPECT_ARGUMENT
	err_expect_argument = 87
	// PM_ERR_EXPECT_EOL_AFTER_STATEMENT
	err_expect_eol_after_statement = 88
	// PM_ERR_EXPECT_EXPRESSION_AFTER_AMPAMPEQ
	err_expect_expression_after_ampampeq = 89
	// PM_ERR_EXPECT_EXPRESSION_AFTER_COMMA
	err_expect_expression_after_comma = 90
	// PM_ERR_EXPECT_EXPRESSION_AFTER_EQUAL
	err_expect_expression_after_equal = 91
	// PM_ERR_EXPECT_EXPRESSION_AFTER_LESS_LESS
	err_expect_expression_after_less_less = 92
	// PM_ERR_EXPECT_EXPRESSION_AFTER_LPAREN
	err_expect_expression_after_lparen = 93
	// PM_ERR_EXPECT_EXPRESSION_AFTER_OPERATOR
	err_expect_expression_after_operator = 94
	// PM_ERR_EXPECT_EXPRESSION_AFTER_PIPEPIPEEQ
	err_expect_expression_after_pipepipeeq = 95
	// PM_ERR_EXPECT_EXPRESSION_AFTER_QUESTION
	err_expect_expression_after_question = 96
	// PM_ERR_EXPECT_EXPRESSION_AFTER_SPLAT
	err_expect_expression_after_splat = 97
	// PM_ERR_EXPECT_EXPRESSION_AFTER_SPLAT_HASH
	err_expect_expression_after_splat_hash = 98
	// PM_ERR_EXPECT_EXPRESSION_AFTER_STAR
	err_expect_expression_after_star = 99
	// PM_ERR_EXPECT_FOR_DELIMITER
	err_expect_for_delimiter = 100
	// PM_ERR_EXPECT_IDENT_REQ_PARAMETER
	err_expect_ident_req_parameter = 101
	// PM_ERR_EXPECT_IN_DELIMITER
	err_expect_in_delimiter = 102
	// PM_ERR_EXPECT_LPAREN_AFTER_NOT_LPAREN
	err_expect_lparen_after_not_lparen = 103
	// PM_ERR_EXPECT_LPAREN_AFTER_NOT_OTHER
	err_expect_lparen_after_not_other = 104
	// PM_ERR_EXPECT_LPAREN_REQ_PARAMETER
	err_expect_lparen_req_parameter = 105
	// PM_ERR_EXPECT_MESSAGE
	err_expect_message = 106
	// PM_ERR_EXPECT_RBRACKET
	err_expect_rbracket = 107
	// PM_ERR_EXPECT_RPAREN
	err_expect_rparen = 108
	// PM_ERR_EXPECT_RPAREN_AFTER_MULTI
	err_expect_rparen_after_multi = 109
	// PM_ERR_EXPECT_RPAREN_REQ_PARAMETER
	err_expect_rparen_req_parameter = 110
	// PM_ERR_EXPECT_SINGLETON_CLASS_DELIMITER
	err_expect_singleton_class_delimiter = 111
	// PM_ERR_EXPECT_STRING_CONTENT
	err_expect_string_content = 112
	// PM_ERR_EXPECT_WHEN_DELIMITER
	err_expect_when_delimiter = 113
	// PM_ERR_EXPRESSION_BARE_HASH
	err_expression_bare_hash = 114
	// PM_ERR_EXPRESSION_NOT_WRITABLE
	err_expression_not_writable = 115
	// PM_ERR_EXPRESSION_NOT_WRITABLE_ENCODING
	err_expression_not_writable_encoding = 116
	// PM_ERR_EXPRESSION_NOT_WRITABLE_FALSE
	err_expression_not_writable_false = 117
	// PM_ERR_EXPRESSION_NOT_WRITABLE_FILE
	err_expression_not_writable_file = 118
	// PM_ERR_EXPRESSION_NOT_WRITABLE_LINE
	err_expression_not_writable_line = 119
	// PM_ERR_EXPRESSION_NOT_WRITABLE_NIL
	err_expression_not_writable_nil = 120
	// PM_ERR_EXPRESSION_NOT_WRITABLE_NUMBERED
	err_expression_not_writable_numbered = 121
	// PM_ERR_EXPRESSION_NOT_WRITABLE_SELF
	err_expression_not_writable_self = 122
	// PM_ERR_EXPRESSION_NOT_WRITABLE_TRUE
	err_expression_not_writable_true = 123
	// PM_ERR_FLOAT_PARSE
	err_float_parse = 124
	// PM_ERR_FOR_COLLECTION
	err_for_collection = 125
	// PM_ERR_FOR_IN
	err_for_in = 126
	// PM_ERR_FOR_INDEX
	err_for_index = 127
	// PM_ERR_FOR_TERM
	err_for_term = 128
	// PM_ERR_GLOBAL_VARIABLE_BARE
	err_global_variable_bare = 129
	// PM_ERR_HASH_EXPRESSION_AFTER_LABEL
	err_hash_expression_after_label = 130
	// PM_ERR_HASH_KEY
	err_hash_key = 131
	// PM_ERR_HASH_ROCKET
	err_hash_rocket = 132
	// PM_ERR_HASH_TERM
	err_hash_term = 133
	// PM_ERR_HASH_VALUE
	err_hash_value = 134
	// PM_ERR_HEREDOC_IDENTIFIER
	err_heredoc_identifier = 135
	// PM_ERR_HEREDOC_TERM
	err_heredoc_term = 136
	// PM_ERR_INCOMPLETE_QUESTION_MARK
	err_incomplete_question_mark = 137
	// PM_ERR_INCOMPLETE_VARIABLE_CLASS
	err_incomplete_variable_class = 138
	// PM_ERR_INCOMPLETE_VARIABLE_CLASS_3_3
	err_incomplete_variable_class_3_3 = 139
	// PM_ERR_INCOMPLETE_VARIABLE_INSTANCE
	err_incomplete_variable_instance = 140
	// PM_ERR_INCOMPLETE_VARIABLE_INSTANCE_3_3
	err_incomplete_variable_instance_3_3 = 141
	// PM_ERR_INSTANCE_VARIABLE_BARE
	err_instance_variable_bare = 142
	// PM_ERR_INVALID_BLOCK_EXIT
	err_invalid_block_exit = 143
	// PM_ERR_INVALID_CHARACTER
	err_invalid_character = 144
	// PM_ERR_INVALID_COMMA
	err_invalid_comma = 145
	// PM_ERR_INVALID_ENCODING_MAGIC_COMMENT
	err_invalid_encoding_magic_comment = 146
	// PM_ERR_INVALID_ESCAPE_CHARACTER
	err_invalid_escape_character = 147
	// PM_ERR_INVALID_FLOAT_EXPONENT
	err_invalid_float_exponent = 148
	// PM_ERR_INVALID_LOCAL_VARIABLE_READ
	err_invalid_local_variable_read = 149
	// PM_ERR_INVALID_LOCAL_VARIABLE_WRITE
	err_invalid_local_variable_write = 150
	// PM_ERR_INVALID_MULTIBYTE_CHAR
	err_invalid_multibyte_char = 151
	// PM_ERR_INVALID_MULTIBYTE_CHARACTER
	err_invalid_multibyte_character = 152
	// PM_ERR_INVALID_MULTIBYTE_ESCAPE
	err_invalid_multibyte_escape = 153
	// PM_ERR_INVALID_NUMBER_BINARY
	err_invalid_number_binary = 154
	// PM_ERR_INVALID_NUMBER_DECIMAL
	err_invalid_number_decimal = 155
	// PM_ERR_INVALID_NUMBER_FRACTION
	err_invalid_number_fraction = 156
	// PM_ERR_INVALID_NUMBER_HEXADECIMAL
	err_invalid_number_hexadecimal = 157
	// PM_ERR_INVALID_NUMBER_OCTAL
	err_invalid_number_octal = 158
	// PM_ERR_INVALID_NUMBER_UNDERSCORE_INNER
	err_invalid_number_underscore_inner = 159
	// PM_ERR_INVALID_NUMBER_UNDERSCORE_TRAILING
	err_invalid_number_underscore_trailing = 160
	// PM_ERR_INVALID_PERCENT
	err_invalid_percent = 161
	// PM_ERR_INVALID_PERCENT_EOF
	err_invalid_percent_eof = 162
	// PM_ERR_INVALID_PRINTABLE_CHARACTER
	err_invalid_printable_character = 163
	// PM_ERR_INVALID_RETRY_AFTER_ELSE
	err_invalid_retry_after_else = 164
	// PM_ERR_INVALID_RETRY_AFTER_ENSURE
	err_invalid_retry_after_ensure = 165
	// PM_ERR_INVALID_RETRY_WITHOUT_RESCUE
	err_invalid_retry_without_rescue = 166
	// PM_ERR_INVALID_SYMBOL
	err_invalid_symbol = 167
	// PM_ERR_INVALID_VARIABLE_GLOBAL
	err_invalid_variable_global = 168
	// PM_ERR_INVALID_VARIABLE_GLOBAL_3_3
	err_invalid_variable_global_3_3 = 169
	// PM_ERR_INVALID_YIELD
	err_invalid_yield = 170
	// PM_ERR_IT_NOT_ALLOWED_NUMBERED
	err_it_not_allowed_numbered = 171
	// PM_ERR_IT_NOT_ALLOWED_ORDINARY
	err_it_not_allowed_ordinary = 172
	// PM_ERR_LAMBDA_OPEN
	err_lambda_open = 173
	// PM_ERR_LAMBDA_TERM_BRACE
	err_lambda_term_brace = 174
	// PM_ERR_LAMBDA_TERM_END
	err_lambda_term_end = 175
	// PM_ERR_LIST_I_LOWER_ELEMENT
	err_list_i_lower_element = 176
	// PM_ERR_LIST_I_LOWER_TERM
	err_list_i_lower_term = 177
	// PM_ERR_LIST_I_UPPER_ELEMENT
	err_list_i_upper_element = 178
	// PM_ERR_LIST_I_UPPER_TERM
	err_list_i_upper_term = 179
	// PM_ERR_LIST_W_LOWER_ELEMENT
	err_list_w_lower_element = 180
	// PM_ERR_LIST_W_LOWER_TERM
	err_list_w_lower_term = 181
	// PM_ERR_LIST_W_UPPER_ELEMENT
	err_list_w_upper_element = 182
	// PM_ERR_LIST_W_UPPER_TERM
	err_list_w_upper_term = 183
	// PM_ERR_MALLOC_FAILED
	err_malloc_failed = 184
	// PM_ERR_MIXED_ENCODING
	err_mixed_encoding = 185
	// PM_ERR_MODULE_IN_METHOD
	err_module_in_method = 186
	// PM_ERR_MODULE_NAME
	err_module_name = 187
	// PM_ERR_MODULE_TERM
	err_module_term = 188
	// PM_ERR_MULTI_ASSIGN_MULTI_SPLATS
	err_multi_assign_multi_splats = 189
	// PM_ERR_MULTI_ASSIGN_UNEXPECTED_REST
	err_multi_assign_unexpected_rest = 190
	// PM_ERR_NESTING_TOO_DEEP
	err_nesting_too_deep = 191
	// PM_ERR_NO_LOCAL_VARIABLE
	err_no_local_variable = 192
	// PM_ERR_NON_ASSOCIATIVE_OPERATOR
	err_non_associative_operator = 193
	// PM_ERR_NOT_EXPRESSION
	err_not_expression = 194
	// PM_ERR_NUMBER_LITERAL_UNDERSCORE
	err_number_literal_underscore = 195
	// PM_ERR_NUMBERED_PARAMETER_INNER_BLOCK
	err_numbered_parameter_inner_block = 196
	// PM_ERR_NUMBERED_PARAMETER_IT
	err_numbered_parameter_it = 197
	// PM_ERR_NUMBERED_PARAMETER_ORDINARY
	err_numbered_parameter_ordinary = 198
	// PM_ERR_NUMBERED_PARAMETER_OUTER_BLOCK
	err_numbered_parameter_outer_block = 199
	// PM_ERR_OPERATOR_MULTI_ASSIGN
	err_operator_multi_assign = 200
	// PM_ERR_OPERATOR_WRITE_ARGUMENTS
	err_operator_write_arguments = 201
	// PM_ERR_OPERATOR_WRITE_BLOCK
	err_operator_write_block = 202
	// PM_ERR_PARAMETER_ASSOC_SPLAT_MULTI
	err_parameter_assoc_splat_multi = 203
	// PM_ERR_PARAMETER_BLOCK_MULTI
	err_parameter_block_multi = 204
	// PM_ERR_PARAMETER_CIRCULAR
	err_parameter_circular = 205
	// PM_ERR_PARAMETER_FORWARDING_AFTER_REST
	err_parameter_forwarding_after_rest = 206
	// PM_ERR_PARAMETER_METHOD_NAME
	err_parameter_method_name = 207
	// PM_ERR_PARAMETER_NAME_DUPLICATED
	err_parameter_name_duplicated = 208
	// PM_ERR_PARAMETER_NO_DEFAULT
	err_parameter_no_default = 209
	// PM_ERR_PARAMETER_NO_DEFAULT_KW
	err_parameter_no_default_kw = 210
	// PM_ERR_PARAMETER_NUMBERED_RESERVED
	err_parameter_numbered_reserved = 211
	// PM_ERR_PARAMETER_ORDER
	err_parameter_order = 212
	// PM_ERR_PARAMETER_SPLAT_MULTI
	err_parameter_splat_multi = 213
	// PM_ERR_PARAMETER_STAR
	err_parameter_star = 214
	// PM_ERR_PARAMETER_UNEXPECTED_FWD
	err_parameter_unexpected_fwd = 215
	// PM_ERR_PARAMETER_UNEXPECTED_NO_KW
	err_parameter_unexpected_no_kw = 216
	// PM_ERR_PARAMETER_WILD_LOOSE_COMMA
	err_parameter_wild_loose_comma = 217
	// PM_ERR_PATTERN_ARRAY_MULTIPLE_RESTS
	err_pattern_array_multiple_rests = 218
	// PM_ERR_PATTERN_CAPTURE_DUPLICATE
	err_pattern_capture_duplicate = 219
	// PM_ERR_PATTERN_CAPTURE_IN_ALTERNATIVE
	err_pattern_capture_in_alternative = 220
	// PM_ERR_PATTERN_EXPRESSION_AFTER_BRACKET
	err_pattern_expression_after_bracket = 221
	// PM_ERR_PATTERN_EXPRESSION_AFTER_COMMA
	err_pattern_expression_after_comma = 222
	// PM_ERR_PATTERN_EXPRESSION_AFTER_HROCKET
	err_pattern_expression_after_hrocket = 223
	// PM_ERR_PATTERN_EXPRESSION_AFTER_IN
	err_pattern_expression_after_in = 224
	// PM_ERR_PATTERN_EXPRESSION_AFTER_KEY
	err_pattern_expression_after_key = 225
	// PM_ERR_PATTERN_EXPRESSION_AFTER_PAREN
	err_pattern_expression_after_paren = 226
	// PM_ERR_PATTERN_EXPRESSION_AFTER_PIN
	err_pattern_expression_after_pin = 227
	// PM_ERR_PATTERN_EXPRESSION_AFTER_PIPE
	err_pattern_expression_after_pipe = 228
	// PM_ERR_PATTERN_EXPRESSION_AFTER_RANGE
	err_pattern_expression_after_range = 229
	// PM_ERR_PATTERN_EXPRESSION_AFTER_REST
	err_pattern_expression_after_rest = 230
	// PM_ERR_PATTERN_FIND_MISSING_INNER
	err_pattern_find_missing_inner = 231
	// PM_ERR_PATTERN_HASH_IMPLICIT
	err_pattern_hash_implicit = 232
	// PM_ERR_PATTERN_HASH_KEY
	err_pattern_hash_key = 233
	// PM_ERR_PATTERN_HASH_KEY_DUPLICATE
	err_pattern_hash_key_duplicate = 234
	// PM_ERR_PATTERN_HASH_KEY_INTERPOLATED
	err_pattern_hash_key_interpolated = 235
	// PM_ERR_PATTERN_HASH_KEY_LABEL
	err_pattern_hash_key_label = 236
	// PM_ERR_PATTERN_HASH_KEY_LOCALS
	err_pattern_hash_key_locals = 237
	// PM_ERR_PATTERN_IDENT_AFTER_HROCKET
	err_pattern_ident_after_hrocket = 238
	// PM_ERR_PATTERN_LABEL_AFTER_COMMA
	err_pattern_label_after_comma = 239
	// PM_ERR_PATTERN_REST
	err_pattern_rest = 240
	// PM_ERR_PATTERN_TERM_BRACE
	err_pattern_term_brace = 241
	// PM_ERR_PATTERN_TERM_BRACKET
	err_pattern_term_bracket = 242
	// PM_ERR_PATTERN_TERM_PAREN
	err_pattern_term_paren = 243
	// PM_ERR_PIPEPIPEEQ_MULTI_ASSIGN
	err_pipepipeeq_multi_assign = 244
	// PM_ERR_REGEXP_ENCODING_OPTION_MISMATCH
	err_regexp_encoding_option_mismatch = 245
	// PM_ERR_REGEXP_INCOMPAT_CHAR_ENCODING
	err_regexp_incompat_char_encoding = 246
	// PM_ERR_REGEXP_INVALID_UNICODE_RANGE
	err_regexp_invalid_unicode_range = 247
	// PM_ERR_REGEXP_NON_ESCAPED_MBC
	err_regexp_non_escaped_mbc = 248
	// PM_ERR_REGEXP_PARSE_ERROR
	err_regexp_parse_error = 249
	// PM_ERR_REGEXP_TERM
	err_regexp_term = 250
	// PM_ERR_REGEXP_UNKNOWN_OPTIONS
	err_regexp_unknown_options = 251
	// PM_ERR_REGEXP_UTF8_CHAR_NON_UTF8_REGEXP
	err_regexp_utf8_char_non_utf8_regexp = 252
	// PM_ERR_RESCUE_EXPRESSION
	err_rescue_expression = 253
	// PM_ERR_RESCUE_MODIFIER_VALUE
	err_rescue_modifier_value = 254
	// PM_ERR_RESCUE_TERM
	err_rescue_term = 255
	// PM_ERR_RESCUE_VARIABLE
	err_rescue_variable = 256
	// PM_ERR_RETURN_INVALID
	err_return_invalid = 257
	// PM_ERR_SCRIPT_NOT_FOUND
	err_script_not_found = 258
	// PM_ERR_SINGLETON_FOR_LITERALS
	err_singleton_for_literals = 259
	// PM_ERR_STATEMENT_ALIAS
	err_statement_alias = 260
	// PM_ERR_STATEMENT_POSTEXE_END
	err_statement_postexe_end = 261
	// PM_ERR_STATEMENT_PREEXE_BEGIN
	err_statement_preexe_begin = 262
	// PM_ERR_STATEMENT_UNDEF
	err_statement_undef = 263
	// PM_ERR_STRING_CONCATENATION
	err_string_concatenation = 264
	// PM_ERR_STRING_INTERPOLATED_TERM
	err_string_interpolated_term = 265
	// PM_ERR_STRING_LITERAL_EOF
	err_string_literal_eof = 266
	// PM_ERR_STRING_LITERAL_TERM
	err_string_literal_term = 267
	// PM_ERR_SYMBOL_INVALID
	err_symbol_invalid = 268
	// PM_ERR_SYMBOL_TERM_DYNAMIC
	err_symbol_term_dynamic = 269
	// PM_ERR_SYMBOL_TERM_INTERPOLATED
	err_symbol_term_interpolated = 270
	// PM_ERR_TERNARY_COLON
	err_ternary_colon = 271
	// PM_ERR_TERNARY_EXPRESSION_FALSE
	err_ternary_expression_false = 272
	// PM_ERR_TERNARY_EXPRESSION_TRUE
	err_ternary_expression_true = 273
	// PM_ERR_UNARY_DISALLOWED
	err_unary_disallowed = 274
	// PM_ERR_UNARY_RECEIVER
	err_unary_receiver = 275
	// PM_ERR_UNDEF_ARGUMENT
	err_undef_argument = 276
	// PM_ERR_UNEXPECTED_BLOCK_ARGUMENT
	err_unexpected_block_argument = 277
	// PM_ERR_UNEXPECTED_INDEX_BLOCK
	err_unexpected_index_block = 278
	// PM_ERR_UNEXPECTED_INDEX_KEYWORDS
	err_unexpected_index_keywords = 279
	// PM_ERR_UNEXPECTED_LABEL
	err_unexpected_label = 280
	// PM_ERR_UNEXPECTED_MULTI_WRITE
	err_unexpected_multi_write = 281
	// PM_ERR_UNEXPECTED_PARAMETER_DEFAULT_VALUE
	err_unexpected_parameter_default_value = 282
	// PM_ERR_UNEXPECTED_RANGE_OPERATOR
	err_unexpected_range_operator = 283
	// PM_ERR_UNEXPECTED_SAFE_NAVIGATION
	err_unexpected_safe_navigation = 284
	// PM_ERR_UNEXPECTED_TOKEN_CLOSE_CONTEXT
	err_unexpected_token_close_context = 285
	// PM_ERR_UNEXPECTED_TOKEN_IGNORE
	err_unexpected_token_ignore = 286
	// PM_ERR_UNTIL_TERM
	err_until_term = 287
	// PM_ERR_VOID_EXPRESSION
	err_void_expression = 288
	// PM_ERR_WHILE_TERM
	err_while_term = 289
	// PM_ERR_WRITE_TARGET_IN_METHOD
	err_write_target_in_method = 290
	// PM_ERR_WRITE_TARGET_READONLY
	err_write_target_readonly = 291
	// PM_ERR_WRITE_TARGET_UNEXPECTED
	err_write_target_unexpected = 292
	// PM_ERR_XSTRING_TERM
	err_xstring_term = 293
	// PM_WARN_AMBIGUOUS_BINARY_OPERATOR
	warn_ambiguous_binary_operator = 294
	// PM_WARN_AMBIGUOUS_FIRST_ARGUMENT_MINUS
	warn_ambiguous_first_argument_minus = 295
	// PM_WARN_AMBIGUOUS_FIRST_ARGUMENT_PLUS
	warn_ambiguous_first_argument_plus = 296
	// PM_WARN_AMBIGUOUS_PREFIX_AMPERSAND
	warn_ambiguous_prefix_ampersand = 297
	// PM_WARN_AMBIGUOUS_PREFIX_STAR
	warn_ambiguous_prefix_star = 298
	// PM_WARN_AMBIGUOUS_PREFIX_STAR_STAR
	warn_ambiguous_prefix_star_star = 299
	// PM_WARN_AMBIGUOUS_SLASH
	warn_ambiguous_slash = 300
	// PM_WARN_COMPARISON_AFTER_COMPARISON
	warn_comparison_after_comparison = 301
	// PM_WARN_DOT_DOT_DOT_EOL
	warn_dot_dot_dot_eol = 302
	// PM_WARN_EQUAL_IN_CONDITIONAL
	warn_equal_in_conditional = 303
	// PM_WARN_EQUAL_IN_CONDITIONAL_3_3
	warn_equal_in_conditional_3_3 = 304
	// PM_WARN_END_IN_METHOD
	warn_end_in_method = 305
	// PM_WARN_DUPLICATED_HASH_KEY
	warn_duplicated_hash_key = 306
	// PM_WARN_DUPLICATED_WHEN_CLAUSE
	warn_duplicated_when_clause = 307
	// PM_WARN_FLOAT_OUT_OF_RANGE
	warn_float_out_of_range = 308
	// PM_WARN_IGNORED_FROZEN_STRING_LITERAL
	warn_ignored_frozen_string_literal = 309
	// PM_WARN_INDENTATION_MISMATCH
	warn_indentation_mismatch = 310
	// PM_WARN_INTEGER_IN_FLIP_FLOP
	warn_integer_in_flip_flop = 311
	// PM_WARN_INVALID_CHARACTER
	warn_invalid_character = 312
	// PM_WARN_INVALID_MAGIC_COMMENT_VALUE
	warn_invalid_magic_comment_value = 313
	// PM_WARN_INVALID_NUMBERED_REFERENCE
	warn_invalid_numbered_reference = 314
	// PM_WARN_KEYWORD_EOL
	warn_keyword_eol = 315
	// PM_WARN_LITERAL_IN_CONDITION_DEFAULT
	warn_literal_in_condition_default = 316
	// PM_WARN_LITERAL_IN_CONDITION_VERBOSE
	warn_literal_in_condition_verbose = 317
	// PM_WARN_SHAREABLE_CONSTANT_VALUE_LINE
	warn_shareable_constant_value_line = 318
	// PM_WARN_SHEBANG_CARRIAGE_RETURN
	warn_shebang_carriage_return = 319
	// PM_WARN_UNEXPECTED_CARRIAGE_RETURN
	warn_unexpected_carriage_return = 320
	// PM_WARN_UNREACHABLE_STATEMENT
	warn_unreachable_statement = 321
	// PM_WARN_UNUSED_LOCAL_VARIABLE
	warn_unused_local_variable = 322
	// PM_WARN_VOID_STATEMENT
	warn_void_statement = 323
}

// diagnostic_kind_from_value converts a serialized Prism diagnostic id to DiagnosticKind.
pub fn diagnostic_kind_from_value(value u32) !DiagnosticKind {
	return match value {
		0 { .err_alias_argument }
		1 { .err_alias_argument_numbered_reference }
		2 { .err_ampampeq_multi_assign }
		3 { .err_argument_after_block }
		4 { .err_argument_after_forwarding_ellipses }
		5 { .err_argument_bare_hash }
		6 { .err_argument_block_forwarding }
		7 { .err_argument_block_multi }
		8 { .err_argument_conflict_ampersand }
		9 { .err_argument_conflict_star }
		10 { .err_argument_conflict_star_star }
		11 { .err_argument_formal_class }
		12 { .err_argument_formal_constant }
		13 { .err_argument_formal_global }
		14 { .err_argument_formal_ivar }
		15 { .err_argument_forwarding_unbound }
		16 { .err_argument_no_forwarding_ampersand }
		17 { .err_argument_no_forwarding_ellipses }
		18 { .err_argument_no_forwarding_star }
		19 { .err_argument_no_forwarding_star_star }
		20 { .err_argument_splat_after_assoc_splat }
		21 { .err_argument_splat_after_splat }
		22 { .err_argument_term_paren }
		23 { .err_argument_unexpected_block }
		24 { .err_array_element }
		25 { .err_array_expression }
		26 { .err_array_expression_after_star }
		27 { .err_array_separator }
		28 { .err_array_term }
		29 { .err_begin_lonely_else }
		30 { .err_begin_term }
		31 { .err_begin_upcase_brace }
		32 { .err_begin_upcase_term }
		33 { .err_begin_upcase_toplevel }
		34 { .err_block_param_local_variable }
		35 { .err_block_param_pipe_term }
		36 { .err_block_term_brace }
		37 { .err_block_term_end }
		38 { .err_cannot_parse_expression }
		39 { .err_cannot_parse_string_part }
		40 { .err_case_expression_after_case }
		41 { .err_case_expression_after_when }
		42 { .err_case_match_missing_predicate }
		43 { .err_case_missing_conditions }
		44 { .err_case_term }
		45 { .err_class_in_method }
		46 { .err_class_name }
		47 { .err_class_superclass }
		48 { .err_class_term }
		49 { .err_class_unexpected_end }
		50 { .err_class_variable_bare }
		51 { .err_conditional_elsif_predicate }
		52 { .err_conditional_if_predicate }
		53 { .err_conditional_predicate_term }
		54 { .err_conditional_term }
		55 { .err_conditional_term_else }
		56 { .err_conditional_unless_predicate }
		57 { .err_conditional_until_predicate }
		58 { .err_conditional_while_predicate }
		59 { .err_constant_path_colon_colon_constant }
		60 { .err_def_endless }
		61 { .err_def_endless_parameters }
		62 { .err_def_endless_setter }
		63 { .err_def_name }
		64 { .err_def_params_term }
		65 { .err_def_params_term_paren }
		66 { .err_def_receiver }
		67 { .err_def_receiver_term }
		68 { .err_def_term }
		69 { .err_defined_expression }
		70 { .err_embdoc_term }
		71 { .err_embexpr_end }
		72 { .err_embvar_invalid }
		73 { .err_end_upcase_brace }
		74 { .err_end_upcase_term }
		75 { .err_escape_invalid_control }
		76 { .err_escape_invalid_control_repeat }
		77 { .err_escape_invalid_hexadecimal }
		78 { .err_escape_invalid_meta }
		79 { .err_escape_invalid_meta_repeat }
		80 { .err_escape_invalid_unicode }
		81 { .err_escape_invalid_unicode_cm_flags }
		82 { .err_escape_invalid_unicode_list }
		83 { .err_escape_invalid_unicode_literal }
		84 { .err_escape_invalid_unicode_long }
		85 { .err_escape_invalid_unicode_short }
		86 { .err_escape_invalid_unicode_term }
		87 { .err_expect_argument }
		88 { .err_expect_eol_after_statement }
		89 { .err_expect_expression_after_ampampeq }
		90 { .err_expect_expression_after_comma }
		91 { .err_expect_expression_after_equal }
		92 { .err_expect_expression_after_less_less }
		93 { .err_expect_expression_after_lparen }
		94 { .err_expect_expression_after_operator }
		95 { .err_expect_expression_after_pipepipeeq }
		96 { .err_expect_expression_after_question }
		97 { .err_expect_expression_after_splat }
		98 { .err_expect_expression_after_splat_hash }
		99 { .err_expect_expression_after_star }
		100 { .err_expect_for_delimiter }
		101 { .err_expect_ident_req_parameter }
		102 { .err_expect_in_delimiter }
		103 { .err_expect_lparen_after_not_lparen }
		104 { .err_expect_lparen_after_not_other }
		105 { .err_expect_lparen_req_parameter }
		106 { .err_expect_message }
		107 { .err_expect_rbracket }
		108 { .err_expect_rparen }
		109 { .err_expect_rparen_after_multi }
		110 { .err_expect_rparen_req_parameter }
		111 { .err_expect_singleton_class_delimiter }
		112 { .err_expect_string_content }
		113 { .err_expect_when_delimiter }
		114 { .err_expression_bare_hash }
		115 { .err_expression_not_writable }
		116 { .err_expression_not_writable_encoding }
		117 { .err_expression_not_writable_false }
		118 { .err_expression_not_writable_file }
		119 { .err_expression_not_writable_line }
		120 { .err_expression_not_writable_nil }
		121 { .err_expression_not_writable_numbered }
		122 { .err_expression_not_writable_self }
		123 { .err_expression_not_writable_true }
		124 { .err_float_parse }
		125 { .err_for_collection }
		126 { .err_for_in }
		127 { .err_for_index }
		128 { .err_for_term }
		129 { .err_global_variable_bare }
		130 { .err_hash_expression_after_label }
		131 { .err_hash_key }
		132 { .err_hash_rocket }
		133 { .err_hash_term }
		134 { .err_hash_value }
		135 { .err_heredoc_identifier }
		136 { .err_heredoc_term }
		137 { .err_incomplete_question_mark }
		138 { .err_incomplete_variable_class }
		139 { .err_incomplete_variable_class_3_3 }
		140 { .err_incomplete_variable_instance }
		141 { .err_incomplete_variable_instance_3_3 }
		142 { .err_instance_variable_bare }
		143 { .err_invalid_block_exit }
		144 { .err_invalid_character }
		145 { .err_invalid_comma }
		146 { .err_invalid_encoding_magic_comment }
		147 { .err_invalid_escape_character }
		148 { .err_invalid_float_exponent }
		149 { .err_invalid_local_variable_read }
		150 { .err_invalid_local_variable_write }
		151 { .err_invalid_multibyte_char }
		152 { .err_invalid_multibyte_character }
		153 { .err_invalid_multibyte_escape }
		154 { .err_invalid_number_binary }
		155 { .err_invalid_number_decimal }
		156 { .err_invalid_number_fraction }
		157 { .err_invalid_number_hexadecimal }
		158 { .err_invalid_number_octal }
		159 { .err_invalid_number_underscore_inner }
		160 { .err_invalid_number_underscore_trailing }
		161 { .err_invalid_percent }
		162 { .err_invalid_percent_eof }
		163 { .err_invalid_printable_character }
		164 { .err_invalid_retry_after_else }
		165 { .err_invalid_retry_after_ensure }
		166 { .err_invalid_retry_without_rescue }
		167 { .err_invalid_symbol }
		168 { .err_invalid_variable_global }
		169 { .err_invalid_variable_global_3_3 }
		170 { .err_invalid_yield }
		171 { .err_it_not_allowed_numbered }
		172 { .err_it_not_allowed_ordinary }
		173 { .err_lambda_open }
		174 { .err_lambda_term_brace }
		175 { .err_lambda_term_end }
		176 { .err_list_i_lower_element }
		177 { .err_list_i_lower_term }
		178 { .err_list_i_upper_element }
		179 { .err_list_i_upper_term }
		180 { .err_list_w_lower_element }
		181 { .err_list_w_lower_term }
		182 { .err_list_w_upper_element }
		183 { .err_list_w_upper_term }
		184 { .err_malloc_failed }
		185 { .err_mixed_encoding }
		186 { .err_module_in_method }
		187 { .err_module_name }
		188 { .err_module_term }
		189 { .err_multi_assign_multi_splats }
		190 { .err_multi_assign_unexpected_rest }
		191 { .err_nesting_too_deep }
		192 { .err_no_local_variable }
		193 { .err_non_associative_operator }
		194 { .err_not_expression }
		195 { .err_number_literal_underscore }
		196 { .err_numbered_parameter_inner_block }
		197 { .err_numbered_parameter_it }
		198 { .err_numbered_parameter_ordinary }
		199 { .err_numbered_parameter_outer_block }
		200 { .err_operator_multi_assign }
		201 { .err_operator_write_arguments }
		202 { .err_operator_write_block }
		203 { .err_parameter_assoc_splat_multi }
		204 { .err_parameter_block_multi }
		205 { .err_parameter_circular }
		206 { .err_parameter_forwarding_after_rest }
		207 { .err_parameter_method_name }
		208 { .err_parameter_name_duplicated }
		209 { .err_parameter_no_default }
		210 { .err_parameter_no_default_kw }
		211 { .err_parameter_numbered_reserved }
		212 { .err_parameter_order }
		213 { .err_parameter_splat_multi }
		214 { .err_parameter_star }
		215 { .err_parameter_unexpected_fwd }
		216 { .err_parameter_unexpected_no_kw }
		217 { .err_parameter_wild_loose_comma }
		218 { .err_pattern_array_multiple_rests }
		219 { .err_pattern_capture_duplicate }
		220 { .err_pattern_capture_in_alternative }
		221 { .err_pattern_expression_after_bracket }
		222 { .err_pattern_expression_after_comma }
		223 { .err_pattern_expression_after_hrocket }
		224 { .err_pattern_expression_after_in }
		225 { .err_pattern_expression_after_key }
		226 { .err_pattern_expression_after_paren }
		227 { .err_pattern_expression_after_pin }
		228 { .err_pattern_expression_after_pipe }
		229 { .err_pattern_expression_after_range }
		230 { .err_pattern_expression_after_rest }
		231 { .err_pattern_find_missing_inner }
		232 { .err_pattern_hash_implicit }
		233 { .err_pattern_hash_key }
		234 { .err_pattern_hash_key_duplicate }
		235 { .err_pattern_hash_key_interpolated }
		236 { .err_pattern_hash_key_label }
		237 { .err_pattern_hash_key_locals }
		238 { .err_pattern_ident_after_hrocket }
		239 { .err_pattern_label_after_comma }
		240 { .err_pattern_rest }
		241 { .err_pattern_term_brace }
		242 { .err_pattern_term_bracket }
		243 { .err_pattern_term_paren }
		244 { .err_pipepipeeq_multi_assign }
		245 { .err_regexp_encoding_option_mismatch }
		246 { .err_regexp_incompat_char_encoding }
		247 { .err_regexp_invalid_unicode_range }
		248 { .err_regexp_non_escaped_mbc }
		249 { .err_regexp_parse_error }
		250 { .err_regexp_term }
		251 { .err_regexp_unknown_options }
		252 { .err_regexp_utf8_char_non_utf8_regexp }
		253 { .err_rescue_expression }
		254 { .err_rescue_modifier_value }
		255 { .err_rescue_term }
		256 { .err_rescue_variable }
		257 { .err_return_invalid }
		258 { .err_script_not_found }
		259 { .err_singleton_for_literals }
		260 { .err_statement_alias }
		261 { .err_statement_postexe_end }
		262 { .err_statement_preexe_begin }
		263 { .err_statement_undef }
		264 { .err_string_concatenation }
		265 { .err_string_interpolated_term }
		266 { .err_string_literal_eof }
		267 { .err_string_literal_term }
		268 { .err_symbol_invalid }
		269 { .err_symbol_term_dynamic }
		270 { .err_symbol_term_interpolated }
		271 { .err_ternary_colon }
		272 { .err_ternary_expression_false }
		273 { .err_ternary_expression_true }
		274 { .err_unary_disallowed }
		275 { .err_unary_receiver }
		276 { .err_undef_argument }
		277 { .err_unexpected_block_argument }
		278 { .err_unexpected_index_block }
		279 { .err_unexpected_index_keywords }
		280 { .err_unexpected_label }
		281 { .err_unexpected_multi_write }
		282 { .err_unexpected_parameter_default_value }
		283 { .err_unexpected_range_operator }
		284 { .err_unexpected_safe_navigation }
		285 { .err_unexpected_token_close_context }
		286 { .err_unexpected_token_ignore }
		287 { .err_until_term }
		288 { .err_void_expression }
		289 { .err_while_term }
		290 { .err_write_target_in_method }
		291 { .err_write_target_readonly }
		292 { .err_write_target_unexpected }
		293 { .err_xstring_term }
		294 { .warn_ambiguous_binary_operator }
		295 { .warn_ambiguous_first_argument_minus }
		296 { .warn_ambiguous_first_argument_plus }
		297 { .warn_ambiguous_prefix_ampersand }
		298 { .warn_ambiguous_prefix_star }
		299 { .warn_ambiguous_prefix_star_star }
		300 { .warn_ambiguous_slash }
		301 { .warn_comparison_after_comparison }
		302 { .warn_dot_dot_dot_eol }
		303 { .warn_equal_in_conditional }
		304 { .warn_equal_in_conditional_3_3 }
		305 { .warn_end_in_method }
		306 { .warn_duplicated_hash_key }
		307 { .warn_duplicated_when_clause }
		308 { .warn_float_out_of_range }
		309 { .warn_ignored_frozen_string_literal }
		310 { .warn_indentation_mismatch }
		311 { .warn_integer_in_flip_flop }
		312 { .warn_invalid_character }
		313 { .warn_invalid_magic_comment_value }
		314 { .warn_invalid_numbered_reference }
		315 { .warn_keyword_eol }
		316 { .warn_literal_in_condition_default }
		317 { .warn_literal_in_condition_verbose }
		318 { .warn_shareable_constant_value_line }
		319 { .warn_shebang_carriage_return }
		320 { .warn_unexpected_carriage_return }
		321 { .warn_unreachable_statement }
		322 { .warn_unused_local_variable }
		323 { .warn_void_statement }
		else { return error('unknown Prism diagnostic kind: ${value}') }
	}
}

// is_error reports whether this diagnostic kind is a Prism parser error.
pub fn (kind DiagnosticKind) is_error() bool {
	return int(kind) < 294
}

// is_warning reports whether this diagnostic kind is a Prism parser warning.
pub fn (kind DiagnosticKind) is_warning() bool {
	return int(kind) >= 294
}
